---
title: "Tidy Tuesday Plot Script"
author: "robert hickman"
date: "27/07/2020"
output: html_document
---

```{r libraries, warning=FALSE,message=FALSE}
library(tidytuesdayR)
library(tidyverse)
library(ggpubr)
library(gifski)
library(cowplot)
```

```{r directories, warning=FALSE,message=FALSE}
week <- "2020-07-28"
save_dir <- paste0("./static/img/tidytuesday_animations/", week)

if(!exists(save_dir)) {
  dir.create(save_dir)
}
```

```{r funs, warning=FALSE,message=FALSE}
get_next_name <- function(save_dir) {
  plots <- dir(save_dir)
  
  if(length(plots) == 0) return("plot1.png")
  
  next_plot <- max(as.numeric(gsub("(plot)([0-9]*)(.png)", "\\2", plots)) + 1)
  return(paste0("plot", next_plot, ".png"))
}

add_title_func <- function(plot_name) {
  title <- ggdraw() + 
  draw_label(
    paste("TidyTuesday", gsub(".png", "", plot_name), "at", Sys.time()),
    fontface = 'bold',
    x = 0,
    hjust = 0
  ) +
  theme(plot.margin = margin(0, 0, 0, 7))
}

quotey_func <- function(quoted_code, plot_name) {
  p1 <- eval(quoted_code)
  code_string <- paste(quoted_code, collapse = "\n\n") %>%
    gsub("^\\{", "", .) %>%
    gsub("%>%", "%>%\n  ", .) %>%
    gsub(" \\+", " +\n  ", .)
  title <- add_title_func(plot_name)
  
  plot <- plot_grid(
    #title,
    p1, 
    ggpubr::ggparagraph(code_string, size = 8),
    nrow = 1, rel_widths = c(6, 1))
  return(plot)
}

```


Code is written inside the quotation function per pass and then plotted and saved

```{r, eval = FALSE}
img <- png::readPNG(RCurl::getURLContent("https://raw.githubusercontent.com/allisonhorst/palmerpenguins/master/man/figures/lter_penguins.png"))
g <- grid::rasterGrob(img, interpolate=TRUE)
p <- ggplot(mtcars, aes(x = hp, y = mpg)) +
  geom_point(colour = "white") +
  annotation_custom(g, xmin = 200, xmax = 300, ymin = 25, ymax = 32.5) +
  theme_dark()

ggsave(file.path(save_dir, plot))
```

```{r code, warning=FALSE,message=FALSE}
code_ <- quote({
  penguins <- tidytuesdayR::tt_load(week) %>%
    .$penguins %>%
    filter(!is.na(bill_length_mm) & !is.na(bill_depth_mm)) %>%
    mutate(model1_x = (bill_length_mm - mean(bill_length_mm)) / sd(bill_length_mm)) %>%
    group_by(species) %>%
    mutate(model2_x = (bill_length_mm - mean(bill_length_mm)) / sd(bill_length_mm)) %>%
    ungroup()
  
  bayes_model <- brms::brm(bill_depth_mm~model1_x, data = penguins)
  bayes_model_species <- brms::brm(bill_depth_mm~model2_x*species, data = penguins)

  img <- png::readPNG(RCurl::getURLContent("https://raw.githubusercontent.com/allisonhorst/palmerpenguins/master/man/figures/lter_penguins.png"))
  grob <- grid::rasterGrob(img, interpolate=TRUE)
  
  pal <- c("#ff7c00", "#c25ccb", "#057575")
  
  p1 <- penguins %>%
    tidybayes::add_fitted_draws(bayes_model, n = 100) %>%
    ggplot(aes(x = bill_length_mm, y = bill_depth_mm, colour = species)) +
    geom_line(aes(bill_length_mm, .value, group = .draw),alpha = 0.05, size = 3, colour = "red") +
    geom_point(size = 6, alpha = 0.7, colour = "black") +
    annotate("text", x = 55, y = 12.5, label = "A #TidyTuesday submission\nby Robert Hickman") +
    labs(title = "Simpson's paradox: negative correlations between bill length and depth...", x = "Flipper length (mm)", y = "Bill length (mm)") +
    theme_minimal()
    
  p2 <- penguins %>%
    tidybayes::add_fitted_draws(bayes_model_species, n = 100) %>%
    ggplot(aes(x = bill_length_mm, y = bill_depth_mm, colour = species), alpha = 0.6) +
    geom_line(aes(bill_length_mm, .value, group = interaction(.draw, species), color = species),alpha = 0.02, size = 3) +
    geom_point(aes(shape = species), size = 6, alpha = 0.7) +
    scale_colour_manual(values = pal) +
    labs(title = "...but positive correlations once controlling for each group", x = "Bill length (mm)", y = "Bill depth (mm)") +
    annotation_custom(grob, xmin = 30, xmax = 40, ymin = 12.5, ymax = 15.5) +
    theme_minimal() +
    theme(legend.position = "bottom")
  
  p <- plot_grid(p1, p2, ncol = 1)

})

plot_name <- get_next_name(save_dir)
p <- quotey_func(code_, plot_name)
ggsave(file.path(save_dir, plot_name), p, width = 540, height = 360, units = "mm")

```



After being finished, create an animation showing the progress. Not run upon running the rmarkdown script

```{r create_animation, warning=FALSE,message=FALSE,eval=FALSE}
png_files <- list.files(save_dir, pattern = ".*png$", full.names = TRUE)
hz <- 0.1
pause <- 3
interesting_plots <- c(1, length(png_files))
reps <- rep(1, length(png_files))
reps[interesting_plots] <- pause / hz

animation_files <- rep(png_files, reps)

gifski(animation_files, gif_file = file.path(save_dir, "tidytuesday_anamiation.gif"), width = 800, height = 600, delay = hz)


```

