---
title: "Untitled"
output: html_document
---
```{r libraries, warning=FALSE,message=FALSE}
library(Rcpp)
```

# Day 1, part 1

```{r load_data, warning=FALSE,message=FALSE}
data1 <- read.table("../../static/files/code_advent/day1_inputs.txt")$V1
```

```{r get_fuel_R, warning=FALSE,message=FALSE}
round_mass <- function(mass) {
  div_3_sub_2 <- floor((mass / 3) - 2)
  return(div_3_sub_2)
}

fuel_per_object <- lapply(data1, round_mass)
total_fuel <- do.call(sum, fuel_per_object)
print(total_fuel)

```


```{r get_fuel_Cpp, warning=FALSE,message=FALSE}
cppFunction('int rounds_massCpp(int mass) {
  //c++ always rounds down as converts to int but still
  int leftover = mass % 3;
  int mass_divisible = mass - leftover;
  int thrice_divided = mass_divisible / 3;
  int sub_two = thrice_divided - 2;
  
  return sub_two;
}')

fuel_per_object <- lapply(data1, rounds_massCpp)
total_fuel <- do.call(sum, fuel_per_object)
print(total_fuel)

```

# Day 1, part 2


```{r whileloop_extra_fuel, warning=FALSE,message=FALSE}
cppFunction('int find_extra_fuelCpp(int mass) {
  //c++ always rounds down as converts to int but still
  int leftover = mass % 3;
  int mass_divisible = mass - leftover;
  int thrice_divided = mass_divisible / 3;
  int mass_fuel = thrice_divided - 2;

  //part two
  int fuel_fuel = (mass_fuel / 3) - 2;
  if(fuel_fuel < 0) fuel_fuel = 0;
  while (fuel_fuel > 2*3 ) {
    mass_fuel = mass_fuel + fuel_fuel;
    fuel_fuel = (fuel_fuel / 3) - 2;
  }
  if(fuel_fuel < 0) fuel_fuel = 0;
  mass_fuel = mass_fuel + fuel_fuel;

  return mass_fuel;
}')

actual_fuel_per_object <- lapply(data1, find_extra_fuelCpp)
actual_total_fuel <- do.call(sum, actual_fuel_per_object)
print(actual_total_fuel)

```

```{r recursive_extra_fuel_R, warning=FALSE,message=FALSE}
recurse_extra_fuel <- function(mass, fuel_counter) {
  missing_fuel <- floor(mass / 3) - 2
  
  if(missing_fuel > 0) {
    fuel_counter <- fuel_counter + missing_fuel
    recurse_extra_fuel(missing_fuel, fuel_counter)
  } else {
    return(fuel_counter)
  }
}

extra_fuel <- lapply(fuel_per_object, recurse_extra_fuel, fuel_counter = 0)
actual_total_fuel <- total_fuel + do.call(sum, extra_fuel)
print(actual_total_fuel)

```


```{r recursive_extra_fuel, warning=FALSE,message=FALSE}
cppFunction('double recurse_extra_fuelCpp(double fuel_mass, double fuel_counter) {
  double missing_fuel = floor(fuel_mass / 3) - 2;
  if(missing_fuel > 0) {
    fuel_counter = fuel_counter + missing_fuel;
    recurse_extra_fuelCpp(missing_fuel, fuel_counter);
  } else {
    return fuel_counter;
  }
}')

extra_fuel <- lapply(fuel_per_object, recurse_extra_fuelCpp, fuel_counter = 0)
actual_total_fuel <- total_fuel + do.call(sum, extra_fuel)
print(actual_total_fuel)

```

# Day 2, part 1

```{r}
data2 <- as.numeric(read.table("../../static/files/code_advent/day2_inputs.txt", sep = ","))
```

```{r}
parse_alarm <- function(data, input1 = NA, input2 = NA, function_length = 4, verbose = T) {
  if(!is.na(input1) & !is.na(input2)) {
    data[2] <- input1; data[3] <- input2
  }
  
  function_tracker <- 1
  
  repeat {
    func <- data[function_tracker]
    
    if(func == 1) {
      output <- data[data[function_tracker + 1] + 1] + data[data[function_tracker + 2] + 1]
    } else if(func == 2) {
      output <- data[data[function_tracker + 1] + 1] * data[data[function_tracker + 2] + 1]
    } else if(func == 99) {
      if(verbose) {
        message("exiting program!")
      }
      break
    } else {
      warning(paste("undefined function:", func))
      break
    }
    
    output_location <- data[function_tracker + 3] + 1
    data[output_location] <- output
    
    function_tracker <- function_tracker + function_length
  }
  
  if(data[1] == 19690720) {
    message(paste("found your desired inputs at:", input1, input2))
  }
  
  answer <- data[1]
  return(answer)
}
```

```{r}
answer1 <- parse_alarm(data = data2, input1 = 12, input2 = 02)

answer1
```


```{r, warning=FALSE}
values_table <- expand.grid(0:99, 0:99)

x <- mapply(parse_alarm,
       values_table$Var1, values_table$Var2,
       MoreArgs = list(data = data2, function_length = 4, verbose = F))

```

```{r}
answer <- values_table[which(x == 19690720),]

100 * answer$Var1 + answer$Var2
```

