---
title: Racing Bar Charts and Some Gnarly data.table Munging
author: Robert Hickman
date: '2019-11-17'
slug: racing_bar_charts
output: pdf_document
categories: []
tags:
  - R
  - bar_charts
  - data.table
header:
  caption: ''
  image: ''
---

# Reproducing Racing Bar Charts in R

text

```{r, warning=FALSE,message=FALSE}
library(tidyverse)
library(gganimate)
library(tweenr)
library(stringi)
library(countrycode)
```

```{r get_city_data, warning=FALSE,message=FALSE}
#read in data from blog repo
city_data <- read.csv("https://raw.githubusercontent.com/RobWHickman/netlify_blog/race_bar_charts/static/files/racing_bar_charts/city_populations.csv", 
                 encoding = "UTF-8", stringsAsFactors = FALSE)

head(city_data)
```

```{r munge_city_data1, warning=FALSE,message=FALSE}
city_data <- city_data %>%
  #select out relevant columns
  select(country_id = Country.Code, country = Country.or.area,
         city_id = City.Code, city = Urban.Agglomeration,
         X1950, X1955, X1960, X1965, X1970, X1975, X1980, X1985, X1990,
         X1995, X2000, X2005, X2010, X2015, X2020, X2025, X2030) %>%
  #melt the data to long format
  reshape2::melt(id.vars = c("country_id", "country", "city_id", "city"),
                 variable.name = "year", value.name = "population") %>%
  #conver the data into usuable numbers
  mutate(year = as.numeric(gsub("^X", "", year)),
         population = as.numeric(gsub(",", "", population)),
         #convert the text into utf-8 readable
         city = stri_trans_general(city, "latin-ascii")) %>%
  #extract the english names for cities
  mutate(city_name = case_when(
    grepl("\\(", city) ~ str_extract(city,  "(?<=\\().+?(?=\\))"),
    grepl("-", city) ~ gsub("-.*", "", city),
    TRUE ~ as.character(city)
  ))

head(city_data)
```

```{r order_cities_by_year, warning=FALSE,message=FALSE}
city_data <- city_data %>%
  #group by and find order at any point
  group_by(year) %>%
  arrange(-population) %>%
  mutate(order = row_number()) %>%
  ungroup()

head(city_data)
```

```{r get_continent, warning=FALSE,message=FALSE}
#get the id data for each unique city
id_data <- city_data %>%
  select(city_id, city_name, country_id, country) %>%
  unique() %>%
  #find the continent of each city
  mutate(continent = countrycode(.$country, origin = "country.name", destination = "continent"))

```

```{r tween_data, warning=FALSE,message=FALSE}
#the number of frames the output will contain
frames <- 500

#use tweenr to manually make the naimation frame data
frame_data <- city_data %>%
  group_by(year) %>%
  arrange(-population) %>%
  mutate(order = row_number()) %>%
  #tweenr stuff here
  select(city_id, year, population, order) %>%
  mutate(ease = "linear") %>%
  tween_elements(., "year", "city_id", "ease", nframes= frames) %>%
  #select out columns
  select(population, order, year, .frame, city_id = .group) %>%
  #merge in id data
  merge(., id_data, by = 'city_id') %>%
  #munge population numbers
  mutate(pop = round(population/1000, 2))

head(frame_data)
```

```{r plot_and_gif_city_data, warning=FALSE,message=FALSE}
p_cities <- frame_data %>%
  #only want to plot the top 10
  filter(order < 10.8) %>%
  ggplot(aes(y = order, x = pop)) +
  #hack to plot the moving bars
  #from v helpful answer at
  #https://stackoverflow.com/questions/53162821/
  #animated-sorted-bar-chart-with-bars-overtaking-each-other/53163549
  geom_tile(aes(x = pop/2, width = pop, fill = continent),
            alpha = 0.8, colour = "black", height = 0.9) +
  geom_text(aes(label = sprintf("%1.2f",pop)), hjust = 1) +
  geom_text(aes(x = 0, label = paste(city_name, " ")),
            vjust = 0.2, hjust = 1) +
  #add labels to plot
  labs(title='{round(as.numeric(closest_state))}',
       x = "Population (millions)", y = "") +
  #y limits at 0-10.5
  #don't clip as will screw the labels outside the plot
  coord_cartesian(ylim = c(0,10.5), clip = "off") +
  #flip the y axis
  scale_y_reverse(position = "left") +
  #theme stuff
  #taken from same stackoverflow answer
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0, size = 22),
        axis.ticks.y = element_blank(),
        axis.text.y  = element_blank(), 
        #make sure labels will be visible
        plot.margin = margin(0,0,0,2.5, "cm")) +
  #transition by our calculated year
  transition_states(year, transition_length = 1, state_length = 0) +
  #scale x axis as pop increases
  view_follow(fixed_y = TRUE) +
  #fade as bares enter and exit the plot
  exit_fade() +
  enter_fade()

#animate the gif
city_gif <- animate(p_cities, frames, start_pause = 0.5, end_pause = 1)
#e.g. if you want to save the output
#anim_save("city_gif.gif", gif)
```

```{r plot_city_gif, warning=FALSE,message=FALSE}
city_gif
```

# The Next Level

```{r extra_libraries, warning=FALSE,message=FALSE}
#use James Curley's engsoccer data for the match data
library(engsoccerdata)
#this file will be in the next version of engsoccerdata but isn't at time of writing
club_data <- read.csv("https://raw.githubusercontent.com/RobWHickman/netlify_blog/race_bar_charts/static/files/racing_bar_charts/england_club_data.csv",
                      stringsAsFactors = FALSE)

#data.table and zoo for munging
library(data.table)
library(zoo)

```

```{r get_match_data}
match_data <- engsoccerdata::england %>%
  mutate(date = as.Date(Date)) %>%
  select(date, season = Season, home, visitor, tier, hgoal, vgoal, result) %>%
  mutate(K = (5-tier) * 10) %>%
  mutate(G = case_when(
    abs(hgoal-vgoal) < 2 ~ 1,
    abs(hgoal-vgoal) < 3 ~ 1.5,
    abs(hgoal-vgoal) >= 3 ~ (11 + abs(hgoal-vgoal)) / 8
  )) %>%
  mutate(result = case_when(
    result == "H" ~ 1,
    result == "A" ~ 0,
    result == "D" ~ 0.5
  )) %>%
  arrange(date)

head(match_data)
```
```{r set_up_ELO, warning=FALSE,message=FALSE,eval=FALSE}
#start all teams with an ELO of 1000
team_ratings <- data.frame(team = unique(match_data$home),
                           rating = 1000)

#function to calculate team ELO and update back to the ratings df
calc_ELO <- function(row) {
  #get the difference in ratings
  hr <- team_ratings$rating[which(team_ratings$team == row$home)]
  vr <- team_ratings$rating[which(team_ratings$team == row$visitor)]
  dr <- (hr + 100) - vr
  
  e_result <- 1/ (10^(-dr/400)+1)
  new_hr <- hr + ((row$K*row$G) * (row$result - e_result))
  new_vr <- vr + ((row$K*row$G) * ((1-row$result) - (1-e_result)))
  
  team_ratings$rating[which(team_ratings$team == row$home)] <<- new_hr
  team_ratings$rating[which(team_ratings$team == row$visitor)] <<- new_vr
  
  output_row <- row %>%
    mutate(h_rating = new_hr, v_rating = new_vr)
  
  return(output_row)
}

#split and lapply function
elo_data <- match_data %>%
  split(f = seq(nrow(.))) %>%
  lapply(., calc_ELO) %>%
  do.call(rbind, .)

#melt the elo data
melt <- elo_data %>%
  select(date, season, home, visitor, h_rating, v_rating) %>%
  reshape2::melt(id.vars = c("date", "season", "h_rating", "v_rating"),
                 variable.name = "location", value.name = "team") %>%
  mutate(rating = case_when(
    location == "home" ~ h_rating,
    location == "visitor" ~ v_rating
  )) %>%
  select(date, season, team, rating)

#df of each teams rating after each game day
head(melted_elo_data)
```

```{r load_elo_data, warning=FALSE,message=FALSE,echo=FALSE}
melted_elo_data <- readRDS("../../static/files/racing_bar_charts/melted_elo_data.rds")
```


```{r munge_football_data, warning=FALSE,message=FALSE}
#init the days we want to run the race over
days <- data.table(date = seq.Date(
  min(melted_elo_data$date), 
  max(melted_elo_data$date),
  by = "day")
  )

munged_football_data <- melted_elo_data %>%
  #start by merging in all the "missing" days
  #ie. days where matches were not played
  merge.data.frame(., days, all.y = TRUE) %>%
  #complete by team in dataset
  complete(date, nesting(team)) %>%
  #delete the completion of NA data
  filter(!is.na(team)) %>%
  #set as DT for munging
  setDT()

munged_football_dt <- munged_football_data %>%
  #order by date
  .[order(date)] %>%
  #find the first game in any league for each season
  .[.[!is.na(season), .I[which.min(date)], by = c("season")]$V1, actual_season := season] %>%
  #fill down
  .[order(date, actual_season), actual_season := na.locf(actual_season, na.rm = FALSE)]
```

```{r remove_season_breaks, warning=FALSE,message=FALSE}
#subset season breaks out
munged_football_dt <- munged_football_dt %>%
  #label each game a team players in a season
  .[!is.na(rating), game := 1:.N, by = c("team", "actual_season")] %>%
  #find the first game each team plays in a season
  .[.[, .I[which.min(game)], by = c("team", "actual_season")]$V1, first_game := 1] %>%
  #find the earliest game which is labelled as the first game in a season
  #this is the 'start' of that season
  .[.[first_game == 1, .I[which.min(date)], by = c("actual_season")]$V1, first_date := 1] %>%
  #we'll use a binary 'keep' variable when we delete days in between seasons
  #wil lfill this down later
  .[date %in% unique(date[which(!is.na(.$first_date))]), keep := 1] %>%
  #do the same with the last game played in any division in a season
  .[.[, .I[which.max(game) + 7], by = c("team", "actual_season")]$V1, last_game := 1] %>%
  .[.[last_game == 1, .I[which.max(date)], by = c("actual_season")]$V1, last_date := 1] %>%
  .[date %in% unique(date[which(!is.na(.$last_date))]), keep := 0] %>%
  #fill down the keep value and keep only those with a 1
  .[, keep := na.locf(keep, na.rm = TRUE), by = team] %>%
  .[keep == 1]
```

```{r tweening_ratings, warning=FALSE,message=FALSE}
#tween the ratings between matches
munged_football_dt <- munged_football_dt %>%
  #make sure in date order
  .[order(date)] %>%
  #use tween fill for each team to get intermediate ratings
  .[, rating := tween_fill(rating, ease = "linear"), by = team] %>%
  #for each teams last season in the data frame will be some days overhanging
  #fill these down as rating obviously won't change
  .[actual_season == max(actual_season), rating := na.locf(rating, na.rm = FALSE), by = team] %>%
  #label each unique date as another frame grouped by season
  .[, frame := .GRP, by = date] %>%
  .[frame %% 5 == 1] %>%
  #take the rolling mean over 10 days to smooth out jumps
  .[order(date), roll_rating := frollmean(rating, n = 10, algo = "exact", align = "left"), by = "team"] %>%
  #remove unrated rows
  .[!is.na(roll_rating)]

```

```{r label_frames, warning=FALSE,message=FALSE}
#use decimal labelling for days in each season
munged_football_dt <- munged_football_dt %>%
  .[frame != lag(frame, default = 0), season_frame := 1:.N, by = actual_season] %>%
  #fill down
  .[, season_frame := na.locf(season_frame)] %>%
  #frame is the season plus the amount through that season
  #could probably do something fancy and label as unique days but this suffices
  .[, season_frame := actual_season + season_frame/(max(season_frame) + 1)]

#y axis ordering
football_data <- munged_football_dt %>%
  #order by rolling rating
  .[order(-roll_rating)] %>%
  #only going to take every 10th day
  #order by rating (as with the cities when rating by size)
  .[frame %% 10 == 1, team_order := 1:.N, by = date] %>%
  #use tweenr to make transitions smooth
  .[order(date), order_fill := tween_fill(team_order, ease = "cubic-in-out"), by = team] %>%
  #delete superfluous data
  .[, c("team_order", "keep", "last_game", "last_date", "first_game", "first_date") := NULL] %>%
  .[!is.na(order_fill)]

head(football_data)
```

```{r plotting_football_data, warning=FALSE,message=FALSE}

plotting_data <- club_data %>%
  filter(team %in% football_data$team) %>%
  football_data[., on = "team"] %>%
  #only plot a cutdown here as it takes a while
  filter(date > "2000-07-01") %>%
  #only want to plot the top 10
  filter(order_fill < 10.8)

palette <- plotting_data %>%
  filter(!duplicated(team)) 
fills <- palette %>%
  .$col1 %>%
  `names<-`(palette$team)
cols <- palette %>%
  .$col2 %>%
  `names<-`(palette$team)

p_football <- plotting_data %>%
  ggplot(aes(y = order_fill, x = roll_rating, fill = team, colour = team)) +
  geom_tile(aes(x = roll_rating/2, width = roll_rating),
            alpha = 0.8, height = 0.9, size = 1) +
  geom_text(aes(x = 0, label = paste(short_name, " ")),
            vjust = 0.2, hjust = 1, colour = "black") +
  geom_text(aes(label = sprintf("%1.2f",roll_rating)), hjust = 1.5, colour = "black") +
  scale_fill_manual(values = fills, guide = FALSE) +
  scale_colour_manual(values = cols, guide = FALSE) +
  labs(title='{floor(as.numeric(as.character(current_frame)))}',
       x = "ELO rating", y = "") +
  coord_cartesian(ylim = c(0,10.5), clip = "off") +
  scale_y_reverse(position = "left") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0, size = 22),
        axis.ticks.y = element_blank(),
        axis.text.y  = element_blank(), 
        plot.margin = margin(0,0,0,2.5, "cm")) +
  transition_manual(season_frame) +
  view_follow(fixed_y = TRUE)

football_gif <- animate(p_football, nframes = length(unique(plotting_data$season_frame)), fps = 10)
```
```{r plot_football_gif, warning=FALSE,message=FALSE}
football_gif
```

