---
title: "Untitled"
output: html_document
---

```{r libraries, warning=FALSE,message=FALSE}
library(tidyverse)
library(magrittr)
library(goalmodel)

set.seed(3459)
```

```{r teams, warning=FALSE,message=FALSE}
teams <- c("Arsenal", #5th in the Premier League
           "Blackburn_Rovers", 
           "Coventry_City",
           "Dover_Athletic",
           "Enfield_Town",
           "Frimley_Green")

```


```{r create_fixtures, warning=FALSE,message=FALSE,include=FALSE}
#https://stackoverflow.com/questions/54099990/is-there-an-efficient-algorithm-to-create-this-type-of-schedule
create_fixtures <- function(teams) {
  team1 <- as.character(teams[1])
  other_teams <- as.character(teams[!teams %in% team1])
  length <- length(other_teams)
  
  for(week in seq((length(teams)-1)*2)) {
    
    if(week %% 2 == 0) {
      fixtures <- data.frame(home = c(team1, other_teams[1:2]),
                             away = other_teams[length:3],
                             gameweek = week)
    } else {
      fixtures <- data.frame(home = other_teams[length:3],
                             away = c(team1, other_teams[1:2]),
                             gameweek = week)
      
    }
    
    if(week == 1) {
      fixtures_df <- fixtures 
    } else {
      fixtures_df <- rbind(fixtures_df, fixtures)
    }
    
    other_teams <- c(other_teams[length], other_teams[1:length-1])
  }
  
  return(fixtures_df)
}

fixtures <- create_fixtures(teams) %>%
  mutate_if(is.factor, as.character)
```

```{r show_fixtures, warning=FALSE,message=FALSE}
head(fixtures)
```


```{r create_results, warning=FALSE,message=FALSE,include=FALSE}
model <- list()
model$parameters <- list(attack = seq(1, -1 + 2/length(teams), by = -2/(length(teams)-1)) %>%
                           append(-sum(.)) %>%
                           `names<-`(teams), 
                         defense = seq(1, -1 + 2/length(teams), by = -2/(length(teams)-1)) %>%
                           append(-sum(.)) %>%
                           `names<-`(teams), 
                         intercept = 0, 
                         hfa = 0.3)

model$all_teams <- teams

model$model <- "poisson"
model$maxgoal <- 8

results <- predict_expg(model, fixtures$home, fixtures$away, return_df = TRUE) %>%
  mutate(noise1 = rnorm(nrow(.), 0, 0.6),
         noise2 = rnorm(nrow(.), 0, 0.6)) %>%
  mutate(hgoal = round(expg1 + noise1,0 ),
         agoal = round(expg2 + noise2,0),
         home = as.factor(team1),
         away = as.factor(team2)) %>%
  merge(., fixtures, by = c("home", "away")) %>%
  mutate_at(vars(hgoal:agoal), funs(replace(., .<0, 0))) %>%
  select(home, away, hgoal, agoal, gameweek) %>%
  arrange(gameweek, home) %>%
  filter(gameweek <= 8)

results
```


```{r}
p1 <- results %>%
  filter(!is.na(hgoal)) %>%
  ggplot(., aes(x = away, y = home, fill = hgoal-agoal)) +
  geom_tile() +
  geom_label(aes(label = paste(hgoal, agoal, sep = "-")), fill = "white") +
  scale_fill_gradient(low = "darkred", high = "green", guide = FALSE) +
  scale_x_discrete(limits = levels(results$home), position = "top") +
  scale_y_discrete(limits = rev(levels(results$away))) +
  theme_minimal()

p1
```


```{r}
melt_results <- function(results_df) {
  results_df %>%
    select(home, away, hgoal, agoal) %>%
    gather(location, team,  -hgoal, -agoal) %>%
    #calculate goals for/against the team
    mutate(g_for = case_when(
      location == "home" ~ hgoal,
      location == "away" ~ agoal
    )) %>%
    mutate(g_ag = case_when(
      location == "home" ~ agoal,
      location == "away" ~ hgoal
    )) 
}

results_to_table <- function(results_df) {
  results_df %>%
    melt_results(.) %>%
  #3 points for a win, 1 for a draw
  mutate(points = case_when(
    g_for > g_ag ~ 3,
    g_ag > g_for ~ 0,
    g_for == g_ag ~ 1
  )) %>%
  #calculate goal difference for each match
  mutate(gd = g_for - g_ag) %>%
  group_by(team) %>%
  #get the final statistics per team
  summarise(games_played = n(),
            gf = sum(g_for),
            ga = sum(g_ag),
            gd = sum(gd),
            points = sum(points)) %>%
  arrange(-points, -gd, -gf)
}

league_table <- results  %>%
  filter(!is.na(hgoal)) %>%
  select(-gameweek) %>%
  results_to_table(.) %>%
  print()

```

```{r}
model <- goalmodel(results$hgoal, results$agoal,  results$home, results$away) %>%
  .$parameters %>%
  print()
```

```{r}
params <- model %>%
  #select team parameters
  .[grepl("defense|attack", names(.))] %>%
  do.call(cbind, .) %>%
  as.data.frame() %>%
  rownames_to_column("team")

#munge the other parameters into text
#the home field advantage and the intercept
other_params <- model %>%
  .[!grepl("defense|attack", names(.))] %>%
  as.data.frame() %>%
  mutate_if(is.numeric, round, 3) %>%
  #glue into one object
  glue::glue_data("intercept: {.$intercept},\n hfa: {.$hfa}")

#plot team paramters over attack/defense axis
p2 <- ggplot(params, aes(x = attack, y = defense, label = team)) +
  #add a best fit linear regression line
  stat_smooth(method = "lm", se = FALSE) +
  geom_point() +
  ggrepel::geom_text_repel(nudge_y = 0.1) +
  #annotate the other parameters in
  annotate("text", y = min(params$defense), x = max(params$attack)*0.6, label = other_params, hjust = 0) +
  theme_minimal()

p2

```

```{r}
library(engsoccerdata)

real_data <- england %>%
  filter(Season > 2000) %>%
  select(home, away = visitor, hgoal, agoal = vgoal) %>%
  melt_results() %>%
  mutate(data = "real")

p3 <- real_data %>%
  ggplot(., aes(x = g_for, fill = location)) +
  geom_density(adjust = 10, alpha = 0.5) +
  scale_fill_manual(values = c("red", "blue")) +
  labs(title = "Goals scored at home and away in English football",
       subtitle = "data from 32.5k matches 2000-2016",
       x = "goals scored",
       y = "density") +
  theme_minimal()

p3
  
```

```{r}
means <- real_data %>%
    group_by(location) %>%
    summarise(mean = mean(g_for))

simulated_poisson <- means %>%
  split(f = .$location) %>%
  lapply(., function(x) df = data.frame(dist = rpois(100000, x$mean),
                                        location = x$location)) %>%
  map_df(I) %>%
  mutate(data = "simulated") 

head(simulated_poisson)

p3 + geom_density(data = simulated_poisson, aes(x = dist, fill = location), adjust = 10, alpha = 0.2) +
  scale_fill_manual(values = c("red", "blue"), guide = FALSE) +
  facet_wrap(~location)
```

```{r}
basic_model <- results %>%
  melt_results() %>%
  group_by(team) %>%
  summarise(av_goals = mean(g_for),
            av_conceed = mean(g_ag)) %>%
  print()
```

```{r}
unplayed_games <- filter(fixtures, gameweek > 8)
```

```{r}
coventry_games <- unplayed_games %>%
  filter(grepl("Coventry_City", home)) %>%
  print()

```

```{r}
attack_parameters <- basic_model$av_goals %>% `names<-`(basic_model$team)

e_results <- paste(attack_parameters[coventry_games$home],
                   attack_parameters[coventry_games$away],
                   sep = "-") %>%
  `names<-`(c(paste(coventry_games$home, coventry_games$away, sep = "-"))) %>%
  print()
```

```{r}
defence_parameters <- basic_model$av_conceed %>% `names<-`(basic_model$team)

e_results <- paste(attack_parameters[coventry_games$home]*defence_parameters[coventry_games$away],
                   attack_parameters[coventry_games$away]*defence_parameters[coventry_games$home],
                   sep = "-") %>%
  `names<-`(c(paste(coventry_games$home, coventry_games$away, sep = "-"))) %>%
  print()

```
```{r}
home_advantage <- mean(results$hgoal, na.rm = TRUE) / mean(results$agoal, na.rm = TRUE)

e_results <- paste(attack_parameters[coventry_games$home]*defence_parameters[coventry_games$away] * home_advantage,
                   attack_parameters[coventry_games$away]*defence_parameters[coventry_games$home],
                   sep = "-") %>%
  `names<-`(c(paste(coventry_games$home, coventry_games$away, sep = "-"))) %>%
  print()

```

```{r}
predict_results <- function(home, away, parameters) {
  e_goals_home <- parameters$attack[home] * parameters$defence[away] * home_advantage
  e_goals_away <- parameters$attack[away] * parameters$defence[home]
  
  df <- data.frame(home = home, away = away, e_hgoal = e_goals_home, e_agoal = e_goals_away)
  
}

basic_parameters <- basic_model %>%
  rename_if(is.numeric, function(x) c("attack", "defence")) %>%
  select(-team) %>%
  as.list() %>%
  lapply(., function(x){names(x) <- teams;return(x)}) %>%
  print()
  

```

```{r}
results2 <- map2_df(unplayed_games$home, unplayed_games$away, 
                    predict_results,
                    basic_parameters)

```

```{r}
e_results <- map2_df(results$home, results$away, 
          predict_results,
          basic_parameters) 
```

```{r}
likelihoods <- data.frame(lik_hgoal = dpois(results$hgoal, e_results$e_hgoal, log = TRUE),
                          lik_agoal = dpois(results$agoal, e_results$e_agoal, log = TRUE)) %>%
  cbind(results, . ) %>%
  merge(., e_results, by = c("home", "away")) %>%
  select(home, away, hgoal, e_hgoal, lik_hgoal, agoal, e_agoal, lik_agoal)
```

```{r}
log_likehood = sum(likelihoods$lik_hgoal, likelihoods$lik_agoal)
```

```{r}
basic_parameters$hfa = 0.1
starting_params <- unlist(basic_parameters)

optimise_params <- function(params, results) {
  attack_params <- params %>%
    .[grepl("attack", names(.))] %>%
    `names<-`(teams)
  defence_params <- params %>%
    .[grepl("defence", names(.))] %>%
    `names<-`(teams)
  hfa = params["hfa"]
  
  e_results <- map2_df(results$home,
                       results$away,
                       function(home, away, attack_params, defence_params) {
                         e_home_goals = exp(log(attack_params[home]) + log(defence_params[away]) * log(hfa))
                         e_away_goals = exp(log(attack_params[away]) + log(defence_params[home]))
                         
                         return(data.frame(e_home_goals, e_away_goals))

                    },
                    attack_params = attack_params, defence_params = defence_params)
  
  log_lik_terms <- sum(
    stats::dpois(results$hgoal, lambda = e_results$e_home_goals),
    stats::dpois(results$agoal, lambda = e_results$e_away_goals)
  )
  
  i <<- i + 1
  vals[[i]] <<- params
  liks[[i]] <<- log_lik_terms

  return(log_lik_terms)
}
i <- 0
vals <- list()
liks <- list()

optim_res <- optim(par = starting_params, fn = optimise_params,
                   results = results,
                   method = "BFGS") %>%
  .$par

```

