```{r libraries, warning=FALSE,message=FALSE}
library(tidyverse)
library(magrittr)
library(rvest)

set.seed(3459)
```


```{r testing_phantomjs, warning=FALSE,message=FALSE}
phantom_dir <- "C:/Users/robwh/Desktop/netlify_blog/static/files/phantomjs_scraping"
index_page <- "elo_index.html" %>%
  file.path(phantom_dir, .) 

country_links <- index_page %>%
  read_html() %>%
  html_nodes("#maintable_World a") %>%
  html_attr("href")

split_ratings <- function(r) {
  split_r <- unlist(strsplit(r, ""))
  if(length(split_r) == 8) {
    r1 <- as.numeric(paste0(split_r[1:4], collapse = ""))
    r2 <- as.numeric(paste0(split_r[5:8], collapse = ""))
  } else if(length(split_r) == 7) {
    if(as.numeric(split_r[1]) > 2) {
      r1 <- as.numeric(paste0(split_r[1:3], collapse = ""))
      r2 <- as.numeric(paste0(split_r[4:7], collapse = ""))
    } else {
      r1 <- as.numeric(paste0(split_r[1:4], collapse = ""))
      r2 <- as.numeric(paste0(split_r[5:7], collapse = ""))
    }
  } else {
    r1 <- as.numeric(paste0(split_r[1:3], collapse = ""))
    r2 <- as.numeric(paste0(split_r[4:6], collapse = ""))
  }
  
  df <- data.frame(r1, r2)
}

split_rankings <- function(rnk) {
  ranking1 <- as.numeric(str_extract(gsub("^.*layout", "", gsub("<br>.*", "", rnk)), "[0-9]+"))
  ranking2 <- as.numeric(gsub(".*<br>", "", gsub("<\\/div.*", "", rnk)))
  
  df <- data.frame(ranking1, ranking2)
}

split_teams <- function(t, o) {
  if(!grepl(">\n<a", t)) {
    x <- str_extract(t, ">.*<br><a")
    y <- gsub("^.", "", x)
    home <- gsub("<br><a", "", y)
    away <- o
  } else {
    x <- str_extract(t, "<br>.*</div>")
    y <- gsub("^<br>", "", x)
    away <- gsub("</div>$", "", y)
    home <- o
  }
  df <- data.frame(home, away)
}


convert_date <- function(d) {
  year <- gsub("(^.*)([0-9]{4}$)", "\\2", d)
  monthday <- gsub(year, "", d)
  
  if(!grepl("[0-9]", monthday)) {
    
    if(monthday == "") {
      monthday <- "Jan 1"
    } else {
      monthday <- paste(monthday, 1)
    }
    
    exact_date <- FALSE
  } else {
    exact_date <- TRUE
  }
  
  date <- as.Date(paste(monthday, year), "%b %d %Y") %>%
    as.character()
  
  df <- data.frame(date, exact_date, d)
}

scrape_nation <- function(country) {
  # download the page
  url <- paste0("https://eloratings.net/", country)
  system2("C:/Users/robwh/Downloads/phantomjs-2.1.1-windows/bin/phantomjs.exe", 
          args = c(file.path(phantom_dir, "scrape_ELO.js"), url))
  
  # read in downloaded page
  page <- read_html("elopage.html")
  
  country_name <- page %>%
    html_nodes("#mainheader") %>%
    html_text() %>%
    gsub("Elo Ratings: ", "", .)
  
  opposing <- page %>%
      html_nodes(".r1 a") %>%
      html_text()
  
  teams <- page %>%
      html_nodes(".r1")
  
  fixtures <- map2_df(teams, opposing, split_teams)

  ratings <- page %>%
    html_nodes(".r4") %>%
    html_text() %>%
    map_df(., split_ratings)
  
  rankings <- page %>%
    html_nodes(".r6") %>%
    map_df(., split_rankings)

  dates <- page %>%
    html_nodes(".r0") %>%
    html_text() %>%
    map_df(., convert_date)

  df <- fixtures %>%
    cbind(., ratings) %>%
    cbind(., rankings) %>%
    cbind(., dates) %>%
    mutate(table_country = country_name)
}

i <- list()
j <- list()
x <- map_df(country_links, scrape_nation)
```
