<!DOCTYPE html>
<html lang="en-us">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="theme" content="hugo-academic">
  <meta name="generator" content="Hugo 0.55.6" />
  <meta name="author" content="Robert Hickman">

  
  
  
  
    
      
    
  
  <meta name="description" content="Every so often a question on The Guardian’s The Knowledge football trivia section piques my interest and is amenable to analysis using R. Previously, I looked at club name suffixes and young World Cup winners last August. This week (give or take), a question posed on twitter caught my attention:
@TheKnowledge_GU was just chatting to some colleagues in the kitchen at work about why Essex doesn&#39;t have many big football clubs and it got me thinking.">

  
  <link rel="alternate" hreflang="en-us" href="/post/counties_league_points/">

  


  

  
  
  <meta name="theme-color" content="#0095eb">
  
  
  
  
    
  
  
    
    
      
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css">
      
    
  
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha512-6MXa8B6uaO18Hid6blRMetEIoPqHf7Ux1tnyIQdpt9qI5OACx7C+O3IVTr98vwGnlcg0LOLa02i9Y1HpVhlfiw==" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.1/css/academicons.min.css" integrity="sha512-NThgw3XKQ1absAahW6to7Ey42uycrVvfNfyjqcFNgCmOCQ5AR4AO0SiXrN+8ZtYeappp56lk1WtvjVmEa+VR6A==" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous">
  
  
  
  
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Montserrat:400,700%7cRoboto:400,400italic,700%7cRoboto&#43;Mono">
  
  <link rel="stylesheet" href="/styles.css">
  

  

  
  <link rel="alternate" href="/index.xml" type="application/rss+xml" title="Robert Hickman">
  <link rel="feed" href="/index.xml" type="application/rss+xml" title="Robert Hickman">
  

  <link rel="manifest" href="/site.webmanifest">
  <link rel="icon" type="image/png" href="/img/icon.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/icon-192.png">

  <link rel="canonical" href="/post/counties_league_points/">

  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@robert_squared">
  <meta property="twitter:creator" content="@robert_squared">
  
  <meta property="og:site_name" content="Robert Hickman">
  <meta property="og:url" content="/post/counties_league_points/">
  <meta property="og:title" content="Which English County Has Won the Most Points | Robert Hickman">
  <meta property="og:description" content="Every so often a question on The Guardian’s The Knowledge football trivia section piques my interest and is amenable to analysis using R. Previously, I looked at club name suffixes and young World Cup winners last August. This week (give or take), a question posed on twitter caught my attention:
@TheKnowledge_GU was just chatting to some colleagues in the kitchen at work about why Essex doesn&#39;t have many big football clubs and it got me thinking.">
  <meta property="og:locale" content="en-us">
  
  <meta property="article:published_time" content="2019-01-21T00:00:00&#43;00:00">
  
  <meta property="article:modified_time" content="2019-01-21T00:00:00&#43;00:00">
  

  <script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {
    skipTags: ['script', 'noscript', 'style', 'textarea', 'pre']
  }
});
</script>
<script async type="text/javascript"
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>


  <title>Which English County Has Won the Most Points | Robert Hickman</title>

</head>
<body id="top" data-spy="scroll" data-target="#toc" data-offset="71" >

<nav class="navbar navbar-default navbar-fixed-top" id="navbar-main">
  <div class="container">

    
    <div class="navbar-header">
      
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target=".navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <a class="navbar-brand" href="/">Robert Hickman</a>
    </div>

    
    <div class="collapse navbar-collapse">

      
      
      <ul class="nav navbar-nav navbar-right">
        

        

        
          
        

        <li class="nav-item">
          <a href="/#about">
            
            <span>Home</span>
            
          </a>
        </li>

        
        

        

        
          
        

        <li class="nav-item">
          <a href="/#publications_selected">
            
            <span>Publications</span>
            
          </a>
        </li>

        
        

        

        
          
        

        <li class="nav-item">
          <a href="/#posts">
            
            <span>Posts</span>
            
          </a>
        </li>

        
        

        

        
          
        

        <li class="nav-item">
          <a href="/#projects">
            
            <span>Projects</span>
            
          </a>
        </li>

        
        
      

      
      </ul>

    </div>
  </div>
</nav>


<article class="article" itemscope itemtype="http://schema.org/Article">

  


  <div class="article-container">
    <div class="article-inner">
      <h1 itemprop="name">Which English County Has Won the Most Points</h1>

      

<div class="article-metadata">

  <span class="article-date">
    
    <time datetime="2019-01-21 00:00:00 &#43;0000 UTC" itemprop="datePublished dateModified">
      Jan 21, 2019
    </time>
  </span>
  <span itemscope itemprop="author publisher" itemtype="http://schema.org/Person">
    <meta itemprop="name" content="Robert Hickman">
  </span>

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    9 min read
  </span>
  

  
  

  
  
  
  

  
  
<div class="share-box" aria-hidden="true">
  <ul class="share">
    <li>
      <a class="twitter"
         href="https://twitter.com/intent/tweet?text=Which%20English%20County%20Has%20Won%20the%20Most%20Points&amp;url=%2fpost%2fcounties_league_points%2f"
         target="_blank" rel="noopener">
        <i class="fa fa-twitter"></i>
      </a>
    </li>
    <li>
      <a class="facebook"
         href="https://www.facebook.com/sharer.php?u=%2fpost%2fcounties_league_points%2f"
         target="_blank" rel="noopener">
        <i class="fa fa-facebook"></i>
      </a>
    </li>
    <li>
      <a class="linkedin"
         href="https://www.linkedin.com/shareArticle?mini=true&amp;url=%2fpost%2fcounties_league_points%2f&amp;title=Which%20English%20County%20Has%20Won%20the%20Most%20Points"
         target="_blank" rel="noopener">
        <i class="fa fa-linkedin"></i>
      </a>
    </li>
    <li>
      <a class="weibo"
         href="http://service.weibo.com/share/share.php?url=%2fpost%2fcounties_league_points%2f&amp;title=Which%20English%20County%20Has%20Won%20the%20Most%20Points"
         target="_blank" rel="noopener">
        <i class="fa fa-weibo"></i>
      </a>
    </li>
    <li>
      <a class="email"
         href="mailto:?subject=Which%20English%20County%20Has%20Won%20the%20Most%20Points&amp;body=%2fpost%2fcounties_league_points%2f">
        <i class="fa fa-envelope"></i>
      </a>
    </li>
  </ul>
</div>


  

</div>


      <div class="article-style" itemprop="articleBody">
        


<p>Every so often a question on The Guardian’s <a href="https://www.theguardian.com/football/series/theknowledge">The Knowledge</a> football trivia section piques my interest and is amenable to analysis using R. Previously, I looked at <a href="http://www.robert-hickman.eu/post/the-knowledge-4th-august-2018/">club name suffixes and young World Cup winners</a> last August. This week (give or take), a question posed on twitter caught my attention:</p>
<blockquote class="twitter-tweet" data-lang="en">
<p lang="en" dir="ltr">
<a href="https://twitter.com/TheKnowledge_GU?ref_src=twsrc%5Etfw"><span class="citation">@TheKnowledge_GU</span></a> was just chatting to some colleagues in the kitchen at work about why Essex doesn't have many big football clubs and it got me thinking. If you combined all the points from every league team in the ceremonial counties in England, which county would be on top?
</p>
— BoxBoron (<span class="citation">@Rutland_Walker</span>) <a href="https://twitter.com/Rutland_Walker/status/1082641231853899781?ref_src=twsrc%5Etfw">January 8, 2019</a>
</blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<p>To start with as always load the libraries needed to analyse this</p>
<pre class="r"><code>#get data
library(engsoccerdata)
library(rvest)
#munging
library(tidyverse)
library(magrittr)
#spatial analysis
library(sf)
library(rgdal)
#for plotting maps
library(ggthemes)</code></pre>
<p>The easiest way to get a total of points is using the engsoccerdata:: packages database of every English football match from the top four divisions (this does not include data from the 2017-2018, or 2018-2019 seasons). We can work out the points easily from the goals scored for each team</p>
<pre class="r"><code>#load the data
match_data &lt;- engsoccerdata::england %&gt;%
  #select only the necessary columns and melt
  select(season = Season, home, visitor, hgoal, vgoal, tier) %&gt;%
  reshape2::melt(id.vars = c(&quot;season&quot;, &quot;hgoal&quot;, &quot;vgoal&quot;, &quot;tier&quot;),
                 variable.name = &quot;location&quot;,
                 value.name = &quot;team&quot;) %&gt;%
  #will need to match this to location data so some club names need cleaning
  mutate(team_subbed = case_when(
    team == &quot;Yeovil&quot; ~ &quot;Yeovil Town&quot;,
    team == &quot;AFC Bournemouth&quot; ~ &quot;A.F.C. Bournemouth&quot;,
    team == &quot;Halifax Town&quot; ~ &quot;F.C. Halifax Town&quot;,
    team == &quot;Aldershot&quot; ~ &quot;Aldershot Town F.C&quot;,
    team == &quot;Wimbledon&quot; ~ &quot;A.F.C. Wimbledon&quot;,
    team == &quot;AFC Wimbledon&quot; ~ &quot;A.F.C. Wimbledon&quot;,
    team == &quot;Macclesfield&quot; ~ &quot;Macclesfield Town&quot;,
    team == &quot;Rushden &amp; Diamonds&quot; ~ &quot;A.F.C. Rushden &amp; Diamonds&quot;,
    team == &quot;Milton Keynes Dons&quot; ~ &quot;Milton Keynes&quot;,
    team == &quot;Dagenham and Redbridge&quot; ~ &quot;Dagenham &amp; Redbridge&quot;,
    team == &quot;Stevenage Borough&quot; ~ &quot;Stevenage&quot;
  )) %&gt;%
  #if cleaning isnt required, take original
  mutate(team_subbed = ifelse(is.na(team_subbed), team, team_subbed))

#peek at the data
head(match_data)</code></pre>
<pre><code>##   season hgoal vgoal tier location            team     team_subbed
## 1   1888     1     1    1     home Accrington F.C. Accrington F.C.
## 2   1888     0     2    1     home Accrington F.C. Accrington F.C.
## 3   1888     2     3    1     home Accrington F.C. Accrington F.C.
## 4   1888     5     1    1     home Accrington F.C. Accrington F.C.
## 5   1888     6     2    1     home Accrington F.C. Accrington F.C.
## 6   1888     3     1    1     home Accrington F.C. Accrington F.C.</code></pre>
<p>The 388k (194k matches) data.frame seems daunting, but actually only results in many fewer unique teams that have played at least one match in the top 4 divisions in England</p>
<pre class="r"><code>length(unique(match_data$team_subbed))</code></pre>
<pre><code>## [1] 141</code></pre>
<p>The location of each club can then be found using the wikipedia pages for them/their stadia. This matches 121 of the 141 clubs pretty nicely which is a fairly good percentage all things considered</p>
<pre class="r"><code>#find the links to each clubs wikipedia page
wiki &lt;- read_html(&quot;https://en.wikipedia.org/wiki/List_of_football_clubs_in_England&quot;) %&gt;%
  html_nodes(&quot;td:nth-child(1)&quot;) %&gt;%
  .[which(grepl(&quot;href&quot;, .))]

#get the names for each club
wiki_clubs &lt;- wiki %&gt;% html_text() %&gt;% gsub(&quot; \\(.*\\)$&quot;, &quot;&quot;, .)

#can match 121/141 right off the bat
(unique(match_data$team_subbed) %in% wiki_clubs) %&gt;%
  which() %&gt;%
  length()</code></pre>
<pre><code>## [1] 121</code></pre>
<p>We can find the location of these matching clubs by finding the page for their stadia and then finding the coordinates. It’s a bit of a messy function because I was just jamming stuff together to get data out as best as possible. This takes ~1 minute to run through all 121 teams (for the blog post I actually saved an RDS of the output from this and load it just to save time/server calls)</p>
<pre class="r"><code>matching_club_locations &lt;- wiki %&gt;% 
  #take only the matching clubs
  .[which(wiki_clubs %in% unique(match_data$team_subbed))] %&gt;%
  html_nodes(&quot;a&quot;) %&gt;%
  #get the wiki page link
  html_attr(&quot;href&quot;) %&gt;%
  paste0(&quot;https://en.wikipedia.org&quot;, .) %&gt;%
  #for each club page find the stadium and its coordinates
  lapply(., function(team) {
    link &lt;- read_html(team) %&gt;%
      html_nodes(&quot;.label a&quot;) %&gt;%
      .[1] %&gt;%
      html_attr(&quot;href&quot;) %&gt;% 
      paste0(&quot;https://en.wikipedia.org&quot;,. )
    coords &lt;- link %&gt;%
      read_html() %&gt;% 
      html_nodes(&quot;#coordinates a&quot;) %&gt;%
      html_attr(&quot;href&quot;) %&gt;%
      .[2]
    #if coords not found use NA
    if(is.na(coords)) {
      coord_df &lt;- data.frame(lat = NA,
                             lon = NA)
    } else {
      coords &lt;- coords %&gt;%
        paste0(&quot;https:&quot;, .) %&gt;%
        read_html() %&gt;%
        html_nodes(&quot;.geo&quot;) %&gt;%
        html_text() %&gt;%
        strsplit(., split = &quot;, &quot;)
      coord_df &lt;- data.frame(lat = as.numeric(coords[[1]][1]),
                             lon = as.numeric(coords[[1]][2]))
    }
    return(coord_df)
  })  %&gt;%
  #bind everything together
  do.call(rbind, .) %&gt;%
  #add the club name as a new column
  mutate(team = wiki_clubs[
    which(wiki_clubs %in% unique(match_data$team_subbed))
    ]) %&gt;%
  #filter out missing data
  filter(!is.na(lat) &amp; !is.na(lon))</code></pre>
<p>Which gives us the location of 114 of our 141 clubs. Most of the remaining ones are now-defunct clubs (e.g. Middlesbrough Ironopolis, Leeds City etc.)</p>
<pre class="r"><code>missing_teams &lt;- unique(match_data$team_subbed)[which(!unique(match_data$team_subbed) %in% matching_club_locations$team)]
missing_teams</code></pre>
<pre><code>##  [1] &quot;Accrington F.C.&quot;           &quot;Darwen&quot;                   
##  [3] &quot;Burton Swifts&quot;             &quot;Port Vale&quot;                
##  [5] &quot;Middlesbrough Ironopolis&quot;  &quot;Rotherham Town&quot;           
##  [7] &quot;Burton Wanderers&quot;          &quot;Loughborough&quot;             
##  [9] &quot;Blackpool&quot;                 &quot;New Brighton Tower&quot;       
## [11] &quot;Burton United&quot;             &quot;Leeds City&quot;               
## [13] &quot;Rotherham County&quot;          &quot;Bristol Rovers&quot;           
## [15] &quot;Darlington&quot;                &quot;Wigan Borough&quot;            
## [17] &quot;Aberdare Athletic&quot;         &quot;New Brighton&quot;             
## [19] &quot;Thames&quot;                    &quot;Aldershot Town F.C&quot;       
## [21] &quot;Hereford United&quot;           &quot;Scarborough&quot;              
## [23] &quot;Cheltenham&quot;                &quot;A.F.C. Rushden &amp; Diamonds&quot;
## [25] &quot;Accrington&quot;                &quot;Crawley Town&quot;             
## [27] &quot;Fleetwood Town&quot;</code></pre>
<p>Given it was a Saturday morning where I had nothing better to do, I simply located these clubs home grounds manually and created a data.frame for their locations. It’s not really great practice but whatever.</p>
<p>These are then all bound together and converted to an sf spatial object with the correct projection</p>
<pre class="r"><code>#add in the missing locations
missing_locations &lt;- data.frame(
  lat = c(53.7646, 53.711772, 52.799, 53.049722, 54.5641, 53.42644, 52.8146,
          52.7743, 53.804722, 53.4359, 52.799, 53.7778, 53.428367, 51.48622,
          54.508425, 53.554914, 51.7127, 53.4292, 51.514431, 51.248386,
          52.060719, 54.265478, 51.906158, 52.328033, 53.7646, 51.405083, 53.9165),
  lon = c(-2.358, -2.477292, -1.6354, -2.1925, -1.2456, -1.34377, -1.6335, -1.1992,
          -3.048056, -3.0377, -1.6354, -1.5722, -1.370231, -2.583134, -1.534394,
          -2.650661, -3.4374, -3.0407, 0.034739, -0.754789, -2.717711, -0.418247,
          -2.060211, -0.5999, -2.358, -0.281944, -3.0247),
    team = as.character(missing_teams)
)

#bind together and convert to sf
all_locations &lt;- rbind(matching_club_locations,
                       missing_locations) %&gt;%
  st_as_sf(coords = c(&quot;lon&quot;, &quot;lat&quot;), crs = st_crs(&quot;+init=epsg:4326&quot;)) %T&gt;%
  #make a quick plot of locations for sanity check
  plot()</code></pre>
<p><img src="/post/2019-01-21-The_Knowledge_2_files/figure-html/bind_missing_locations-1.png" width="672" /></p>
<p>Now that we have all the teams, we need the English historical county boundaries to group them by. I’d actually already used these for football analysis, looknig at <a href="https://www.citymetric.com/horizons/football-could-independent-yorkshire-win-world-cup-3961">if an independent Yorkshire could win the World Cup</a>.</p>
<p>Load the data (the boundary file can be download from the <a href="https://www.ordnancesurvey.co.uk/business-and-government/products/boundaryline.html">Ordnance Survey</a>) and make a quick plot of the boundaries and teams</p>
<p>(I also created an sf object engwal which is just the counties from England and Wales selected out for background plotting)</p>
<pre><code>## OGR data source with driver: ESRI Shapefile 
## Source: &quot;C:\Users\Alaa\Desktop\geo_data\boundary\Data\Supplementary_Ceremonial&quot;, layer: &quot;Boundary-line-ceremonial-counties_region&quot;
## with 91 features
## It has 2 fields</code></pre>
<pre class="r"><code>#load the boundary file
counties &lt;- readOGR(dsn = &quot;path/to/file&quot;,
                    layer = &quot;county_boundaries&quot;) %&gt;%
  #convert to sf and project as northing/easting
  st_as_sf(., crs = st_crs(&quot;+init=epsg:27700&quot;)) %&gt;%
  #only interested in the county name
  select(county = NAME) %&gt;%
  #transform the projection to match that of the club locations
  st_transform(., crs = st_crs(&quot;+init=epsg:4326&quot;))

engwal &lt;- counties %&gt;%
  .[c(1:54, 88, 90),]</code></pre>
<pre class="r"><code>#make a quick plot of counties and teams
ggplot() +
  geom_sf(data = counties, fill = NA) +
  geom_sf(data = all_locations) +
  ggtitle(&quot;Location of Teams to have Played Top\n 4 English Football Divisions&quot;) +
  theme_minimal() +
  theme(axis.title=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank())</code></pre>
<p><img src="/post/2019-01-21-The_Knowledge_2_files/figure-html/plot_team_locations-1.png" width="672" /></p>
<p>(by the way the artifacts around Bristol and the Wirral are from the OS dataset- it’s very annoying)</p>
<p>Then we need to determine which teams are within which counties. The easiest way to do this is to use a spatial join of the team names in all_locations by which county they fall into (using st_contains from the sf package)</p>
<pre class="r"><code>#bind the team names to each county
counties %&lt;&gt;%
  st_join(., all_locations, join = st_contains) %&gt;%
  #remove counties that contain zero teams
  filter(!is.na(team)) %&gt;%
  mutate(county = as.character(county))</code></pre>
<pre><code>## although coordinates are longitude/latitude, st_contains assumes that they are planar</code></pre>
<pre class="r"><code>#quick plot of number of teams per county (missing = 0)
counties %&gt;%
  group_by(county) %&gt;%
  summarise(n_clubs = n()) %&gt;%
  ggplot(data = .) +
  geom_sf(data = engwal) +
  geom_sf(aes(fill = n_clubs), colour = &quot;black&quot;) +
  scale_fill_viridis_c(option = &quot;plasma&quot;, name = &quot;# clubs&quot;) +
  ggtitle(&quot;Number of Top 4 Division Playing\n Teams in each Ceremonial County&quot;) +
  theme_minimal() +
  theme(axis.title=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank())</code></pre>
<p><img src="/post/2019-01-21-The_Knowledge_2_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>Which shows that most English historic counties (and a few Welsh ones due to teams like Cardiff City/ Swansea City etc.) have at least 1 team that has competed in the top 4 flights of English football at some point (those that do not are: Isle of Wight, Rutland, Surrey, Warwickshire, West Sussex and Cornwall).</p>
<p>To finally get the total number of points won by these teams, the county data needs to be joined back onto the match data from the top. First I clean it up a bit then make the left_join by team name. Finally the number of points per match is calculated using case_when and points are grouped by county and summed</p>
<pre class="r"><code>county_match_data &lt;- match_data %&gt;% 
  mutate(team = team_subbed) %&gt;%
  select(-team_subbed) %&gt;%
  left_join(., counties, by = &quot;team&quot;) %&gt;%
  mutate(points = case_when(
    location == &quot;home&quot; &amp; hgoal &gt; vgoal ~ 3,
    location == &quot;visitor&quot; &amp; vgoal &gt; hgoal ~ 3,
    location == &quot;home&quot; &amp; hgoal &lt; vgoal ~ 0,
    location == &quot;visitor&quot; &amp; vgoal &lt; hgoal ~ 0,
    hgoal == vgoal ~ 1
  ))

county_points &lt;- county_match_data %&gt;%
  group_by(county) %&gt;%
  summarise(total_points = sum(points))</code></pre>
<p>Perhaps unsurprisingly, the county with the most points is Greater London, with Greater Manchester following and other footballing hotspots/ large counties in the West Midlands, Lancashire and around Yorkshire in the trailing group</p>
<pre class="r"><code>head(arrange(county_points, -total_points))</code></pre>
<pre><code>## # A tibble: 6 x 2
##   county             total_points
##   &lt;chr&gt;                     &lt;dbl&gt;
## 1 Greater London            67189
## 2 Greater Manchester        47203
## 3 West Midlands             37413
## 4 Lancashire                30808
## 5 South Yorkshire           30061
## 6 West Yorkshire            24947</code></pre>
<p>By contrast, Worcestshire and Northumberland barely have any points, with a few Welsh counties also struggling</p>
<pre class="r"><code>head(arrange(county_points, total_points))</code></pre>
<pre><code>## # A tibble: 6 x 2
##   county          total_points
##   &lt;chr&gt;                  &lt;dbl&gt;
## 1 Worcestershire           275
## 2 Northumberland           398
## 3 Mid Glamorgan            744
## 4 Somerset                 813
## 5 Gloucestershire          994
## 6 Herefordshire           1739</code></pre>
<p>If we group by tier as well as county, it’s possible to see how well each county has done at specific tiers.</p>
<pre class="r"><code>county_match_data %&gt;%
  group_by(county, tier) %&gt;%
  summarise(total_points = sum(points)) %&gt;%
  left_join(.,
            select(counties, county),
            by = &quot;county&quot;) %&gt;%
  ggplot(data = .) +
  geom_sf(data = engwal) +
  geom_sf(aes(fill = total_points), colour = &quot;black&quot;) +
  scale_fill_viridis_c(option = &quot;plasma&quot;, name = &quot;total points&quot;) +
  ggtitle(&quot;Number of Points Won by each County\n per Tier of English Football&quot;) +
  facet_wrap(~tier) +
  theme_minimal() +
  theme(axis.title=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank())</code></pre>
<p><img src="/post/2019-01-21-The_Knowledge_2_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>And for the Premier League era this clears up to</p>
<pre class="r"><code>county_match_data %&gt;%
  filter(season &gt; 1991) %&gt;%
  group_by(county, tier) %&gt;%
  summarise(total_points = sum(points)) %&gt;%
  left_join(.,
            select(counties, county),
            by = &quot;county&quot;) %&gt;%
  ggplot(data = .) +
  geom_sf(data = engwal) +
  geom_sf(aes(fill = total_points), colour = &quot;black&quot;, name = &quot;total points&quot;) +
  scale_fill_viridis_c(option = &quot;plasma&quot;) +
  ggtitle(&quot;Number of Points Won by each County\n per Tier of English Football&quot;,
          subtitle = &quot;From Begining of 1992/1993 Season&quot;) +
  facet_wrap(~tier) +
  theme_minimal() +
  theme(axis.title=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank())</code></pre>
<pre><code>## Warning: Ignoring unknown parameters: name</code></pre>
<p><img src="/post/2019-01-21-The_Knowledge_2_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Which shows just how dominant London has been in the top division of English football (especially as it is only competitive at lower levels).</p>
<p>I had wanted to weight points by the average ELO of that league and see which county has the most weight-adjusted points but got bored for this small blog post.</p>
<p>Best,</p>

      </div>

      


<div class="article-tags">
  
  <a class="btn btn-primary btn-outline" href="/tags/rstats">rstats</a>
  
  <a class="btn btn-primary btn-outline" href="/tags/football">football</a>
  
  <a class="btn btn-primary btn-outline" href="/tags/the_knowledge">the_knowledge</a>
  
  <a class="btn btn-primary btn-outline" href="/tags/maps">maps</a>
  
</div>



    </div>
  </div>

</article>



<div class="article-container article-widget">
  <div class="hr-light"></div>
  <h3>Related</h3>
  <ul>
    
    <li><a href="/post/the-knowledge-4th-august-2018/">The Knowledge 4th August 2018</a></li>
    
    <li><a href="/post/yorkshire_world_cup_6/">Could an Independent Yorkshire Win the World Cup - Rest of the World/UK</a></li>
    
    <li><a href="/post/yorkshire_world_cup_5/">Could an Independent Yorkshire Win the World Cup - Simulate World Cups</a></li>
    
    <li><a href="/post/yorkshire_world_cup_4/">Could an Independent Yorkshire Win the World Cup - Picking Teams</a></li>
    
    <li><a href="/post/yorkshire_world_cup_3/">Could an Independent Yorkshire Win the World Cup - Finding British Player&#39;s Birthplaces</a></li>
    
  </ul>
</div>




<div class="article-container">
  

</div>

<footer class="site-footer">
  <div class="container">
    <p class="powered-by">

      &copy; 2018 &middot; 

      Powered by the
      <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
      <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

      <span class="pull-right" aria-hidden="true">
        <a href="#" id="back_to_top">
          <span class="button_icon">
            <i class="fa fa-chevron-up fa-2x"></i>
          </span>
        </a>
      </span>

    </p>
  </div>
</footer>


<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close btn-large" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Cite</h4>
      </div>
      <div>
        <pre><code class="modal-body tex"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary btn-outline js-copy-cite" href="#" target="_blank">
          <i class="fa fa-copy"></i> Copy
        </a>
        <a class="btn btn-primary btn-outline js-download-cite" href="#" target="_blank">
          <i class="fa fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

    

    
    

    

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" integrity="sha512-3P8rXCuGJdNZOnUx/03c1jOTnMn3rP63nBip5gOP2qmUh5YAdVAvFZ1E+QLZZbC1rtMrQb+mah3AfYW11RUrWA==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.3/imagesloaded.pkgd.min.js" integrity="sha512-umsR78NN0D23AzgoZ11K7raBD+R6hqKojyBZs1w8WvYlsI+QuKRGBx3LFCwhatzBunCjDuJpDHwxD13sLMbpRA==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha512-iztkobsvnjKfAtTNdHkGVjAYTrrtlC7mGp/54c40wowO7LhURYl3gVzzcEqGl/qKXQltJ2HwMrdLcNUdo+N/RQ==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.4/isotope.pkgd.min.js" integrity="sha512-VDBOIlDbuC4VWxGJNmuFRQ0Li0SKkDpmGyuhAG5LTDLd/dJ/S0WMVxriR2Y+CyPL5gzjpN4f/6iqWVBJlht0tQ==" crossorigin="anonymous"></script>
    
    
    <script src="/js/hugo-academic.js"></script>
    

    
    
      
      
      <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js" integrity="sha256-/BfiIkHlHoVihZdc6TFuj7MmJ0TWcWsMXkeDFwhi0zw=" crossorigin="anonymous"></script>
      

      

      

      <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({ tex2jax: { inlineMath: [['$','$'], ['\\(','\\)']] } });
    </script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_CHTML" integrity="sha512-tOav5w1OjvsSJzePRtt2uQPFwBoHt1VZcUq8l8nm5284LEKE9FSJBQryzMBzHxY5P0zRdNqEcpLIRVYFNgu1jw==" crossorigin="anonymous"></script>
    
    

  </body>
</html>

