<!DOCTYPE html>
<html lang="en-us">
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="theme" content="hugo-academic">
  <meta name="generator" content="Hugo 0.54.0" />
  <meta name="author" content="Robert Hickman">

  
  
  
  
    
      
    
  
  <meta name="description" content="The first question this week concerns players scoring on (or nearest to) every day of the year
Has any player played/or even scored on every date in a calendar year. What’s the nearest anyone has come?— David Thomson (@thomsonionioni) January 29, 2019Getting the data for this is the main problem. The best (free) source I tend to use is transfermarkt.com, but data there becomes less reliable from before 2000 (and only has a few years of data from more obscure years where I could believe some players are banging in goals for fun).">

  
  <link rel="alternate" hreflang="en-us" href="/post/knowledge_3/">

  


  

  
  
  <meta name="theme-color" content="#0095eb">
  
  
  
  
    
  
  
    
    
      
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css">
      
    
  
  
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha512-6MXa8B6uaO18Hid6blRMetEIoPqHf7Ux1tnyIQdpt9qI5OACx7C+O3IVTr98vwGnlcg0LOLa02i9Y1HpVhlfiw==" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.1/css/academicons.min.css" integrity="sha512-NThgw3XKQ1absAahW6to7Ey42uycrVvfNfyjqcFNgCmOCQ5AR4AO0SiXrN+8ZtYeappp56lk1WtvjVmEa+VR6A==" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous">
  
  
  
  
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Montserrat:400,700%7cRoboto:400,400italic,700%7cRoboto&#43;Mono">
  
  <link rel="stylesheet" href="/styles.css">
  

  

  
  <link rel="alternate" href="/index.xml" type="application/rss+xml" title="Robert Hickman">
  <link rel="feed" href="/index.xml" type="application/rss+xml" title="Robert Hickman">
  

  <link rel="manifest" href="/site.webmanifest">
  <link rel="icon" type="image/png" href="/img/icon.png">
  <link rel="apple-touch-icon" type="image/png" href="/img/icon-192.png">

  <link rel="canonical" href="/post/knowledge_3/">

  <meta property="twitter:card" content="summary_large_image">
  
  <meta property="twitter:site" content="@robert_squared">
  <meta property="twitter:creator" content="@robert_squared">
  
  <meta property="og:site_name" content="Robert Hickman">
  <meta property="og:url" content="/post/knowledge_3/">
  <meta property="og:title" content="THe Knowledge 3 | Robert Hickman">
  <meta property="og:description" content="The first question this week concerns players scoring on (or nearest to) every day of the year
Has any player played/or even scored on every date in a calendar year. What’s the nearest anyone has come?— David Thomson (@thomsonionioni) January 29, 2019Getting the data for this is the main problem. The best (free) source I tend to use is transfermarkt.com, but data there becomes less reliable from before 2000 (and only has a few years of data from more obscure years where I could believe some players are banging in goals for fun).">
  <meta property="og:locale" content="en-us">
  
  <meta property="article:published_time" content="2019-02-05T00:00:00&#43;00:00">
  
  <meta property="article:modified_time" content="2019-02-05T00:00:00&#43;00:00">
  

  <script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {
    skipTags: ['script', 'noscript', 'style', 'textarea', 'pre']
  }
});
</script>
<script async type="text/javascript"
  src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
</script>


  <title>THe Knowledge 3 | Robert Hickman</title>

</head>
<body id="top" data-spy="scroll" data-target="#toc" data-offset="71" >

<nav class="navbar navbar-default navbar-fixed-top" id="navbar-main">
  <div class="container">

    
    <div class="navbar-header">
      
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
              data-target=".navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <a class="navbar-brand" href="/">Robert Hickman</a>
    </div>

    
    <div class="collapse navbar-collapse">

      
      
      <ul class="nav navbar-nav navbar-right">
        

        

        
          
        

        <li class="nav-item">
          <a href="/#about">
            
            <span>Home</span>
            
          </a>
        </li>

        
        

        

        
          
        

        <li class="nav-item">
          <a href="/#publications_selected">
            
            <span>Publications</span>
            
          </a>
        </li>

        
        

        

        
          
        

        <li class="nav-item">
          <a href="/#posts">
            
            <span>Posts</span>
            
          </a>
        </li>

        
        

        

        
          
        

        <li class="nav-item">
          <a href="/#projects">
            
            <span>Projects</span>
            
          </a>
        </li>

        
        

        

        
          
        

        <li class="nav-item">
          <a href="/#writing">
            
            <span>Writing</span>
            
          </a>
        </li>

        
        

        

        
          
        

        <li class="nav-item">
          <a href="/#contact">
            
            <span>Contact</span>
            
          </a>
        </li>

        
        
      

      
      </ul>

    </div>
  </div>
</nav>


<article class="article" itemscope itemtype="http://schema.org/Article">

  


  <div class="article-container">
    <div class="article-inner">
      <h1 itemprop="name">THe Knowledge 3</h1>

      

<div class="article-metadata">

  <span class="article-date">
    
    <time datetime="2019-02-05 00:00:00 &#43;0000 UTC" itemprop="datePublished dateModified">
      Feb 5, 2019
    </time>
  </span>
  <span itemscope itemprop="author publisher" itemtype="http://schema.org/Person">
    <meta itemprop="name" content="Robert Hickman">
  </span>

  
  <span class="middot-divider"></span>
  <span class="article-reading-time">
    19 min read
  </span>
  

  
  

  
  
  
  

  
  
<div class="share-box" aria-hidden="true">
  <ul class="share">
    <li>
      <a class="twitter"
         href="https://twitter.com/intent/tweet?text=THe%20Knowledge%203&amp;url=%2fpost%2fknowledge_3%2f"
         target="_blank" rel="noopener">
        <i class="fa fa-twitter"></i>
      </a>
    </li>
    <li>
      <a class="facebook"
         href="https://www.facebook.com/sharer.php?u=%2fpost%2fknowledge_3%2f"
         target="_blank" rel="noopener">
        <i class="fa fa-facebook"></i>
      </a>
    </li>
    <li>
      <a class="linkedin"
         href="https://www.linkedin.com/shareArticle?mini=true&amp;url=%2fpost%2fknowledge_3%2f&amp;title=THe%20Knowledge%203"
         target="_blank" rel="noopener">
        <i class="fa fa-linkedin"></i>
      </a>
    </li>
    <li>
      <a class="weibo"
         href="http://service.weibo.com/share/share.php?url=%2fpost%2fknowledge_3%2f&amp;title=THe%20Knowledge%203"
         target="_blank" rel="noopener">
        <i class="fa fa-weibo"></i>
      </a>
    </li>
    <li>
      <a class="email"
         href="mailto:?subject=THe%20Knowledge%203&amp;body=%2fpost%2fknowledge_3%2f">
        <i class="fa fa-envelope"></i>
      </a>
    </li>
  </ul>
</div>


  

</div>


      <div class="article-style" itemprop="articleBody">
        


<div id="section" class="section level1">
<h1></h1>
<p>The first question this week concerns players scoring on (or nearest to) every day of the year</p>
<blockquote class="twitter-tweet" data-lang="en">
<p lang="en" dir="ltr">
Has any player played/or even scored on every date in a calendar year. What’s the nearest anyone has come?
</p>
— David Thomson (<span class="citation">@thomsonionioni</span>) <a href="https://twitter.com/thomsonionioni/status/1090206478479298560?ref_src=twsrc%5Etfw">January 29, 2019</a>
</blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<p>Getting the data for this is the main problem. The best (free) source I tend to use is transfermarkt.com, but data there becomes less reliable from before 2000 (and only has a few years of data from more obscure years where I could believe some players are banging in goals for fun).</p>
<p>Nonetheless, it should at least gives us some ideas</p>
<pre class="r"><code>library(rvest)
library(tidyverse)
library(zoo)
library(openair)
library(engsoccerdata)
library(data.table)</code></pre>
<p>For each player sampled we’re going to want the data for each goal scored both for their club and country. Saving the competition data is also useful as it also allows us to sort out friendlies which may or may not count depending on interpretation of the question.</p>
<p>Two quick functions will do this for any given player id</p>
<pre class="r"><code>#create a data frame of club goals
get_club_goals &lt;- function(club_stats) {
  #read the page
  read &lt;- read_html(club_stats)
  
  #get the players names
  name &lt;- read %&gt;%
    html_nodes(&quot;.dataName b&quot;) %&gt;%
    html_text()
    
  #read the table of goals scored and munge together
  club_df &lt;- read %&gt;%
    html_nodes(xpath = &#39;//*[@id=&quot;main&quot;]/div[10]/div/div/div[4]/table&#39;) %&gt;%
    html_table(fill = TRUE) %&gt;%
    as.data.frame() %&gt;%
    select(Date, Minute, Competition.1) %&gt;%
    mutate(minute = as.numeric(gsub(&quot;&#39;.*&quot;, &quot;&quot;, Minute))) %&gt;%
    filter(!is.na(minute)) %&gt;% 
    #convert date to day of the year
    mutate(date = case_when(
      Date != &quot;&quot; ~ strftime(as.Date(Date, &quot;%m/%d/%y&quot;), &quot;%m/%d&quot;)
    )) %&gt;%
    mutate(competition = ifelse(Competition.1 == &quot;&quot;, NA, Competition.1)) %&gt;%
    select(competition, date, minute) %&gt;%
    #fill down the competition and date if missing
    do(na.locf(.)) %&gt;%
    mutate(scored_for = &quot;club&quot;, name = name)
}

#do the same for national team goals
get_nt_goals &lt;- function(nt_stats) {
  read &lt;- read_html(nt_stats)
  
  name &lt;- read %&gt;%
    html_nodes(&quot;.dataName b&quot;) %&gt;%
    html_text()

  goal_table &lt;- read %&gt;%
    html_nodes(xpath = &#39;//*[@id=&quot;main&quot;]/div[10]/div[1]/div[3]/div[4]/table&#39;)
  
  #some players won&#39;t have any national team goals
  #return NA
  if(!is_empty(goal_table)) {
    nt &lt;- goal_table %&gt;%
      html_table(fill = TRUE) %&gt;%
      as.data.frame() %&gt;%
      select(For, Date, Var.11) %&gt;%
      mutate(goals = as.numeric(Var.11)) %&gt;%
      mutate(date = case_when(
        Date != &quot;&quot; ~ strftime(as.Date(Date, &quot;%m/%d/%y&quot;), &quot;%m/%d&quot;)
      )) %&gt;%
      mutate(competition = ifelse(For == &quot;&quot;, NA, For)) %&gt;%
      mutate(competition = na.locf(competition)) %&gt;%
      filter(!is.na(date)) %&gt;%
      select(competition, date, goals) 
    
    #if more than 1 goal is scored on a game it&#39;s counted as two rows
    #separate these out
    if(any(nt$goals != 1)) {
      nt_df &lt;- do.call(&quot;c&quot;, (mapply(rep, c(nt$competition, nt$date), nt$goals))) %&gt;%
        matrix(., 2, byrow = TRUE) %&gt;%
        t() %&gt;%
        as.data.frame() %&gt;%
        select(competition = V1, date = V2)
    } else {
      nt_df &lt;- nt %&gt;%
        select(-goals)
    }
    
    #finish off munging
    df &lt;- nt_df %&gt;%
      mutate(minute = NA, scored_for = &quot;nation&quot;, name = name)
  } else {
    df &lt;- NA
  }
  return(df)
}</code></pre>
<p>Now we can get into the scraping. For each player some parts of the URL stay the same, so lets save those as objects so we don’t have to deal with massive long urls.</p>
<p>I decided to test out the functions using Cristiano Ronaldo as his 675 goals for club and country is (I believe) more than any active player. Pasting the url together and running on the functions does the trick</p>
<pre class="r"><code>#for each player some parts of url stay the same
base_url &lt;- &quot;https://www.transfermarkt.co.uk/&quot;
club_text1 &lt;- &quot;/alletore/spieler/&quot;
club_text2 &lt;- &quot;/saison//verein/0/liga/0/wettbewerb//pos/0/trainer_id/0/minute/0/torart/0/plus/1&quot;
nt_text1 &lt;- &quot;/nationalmannschaft/spieler/&quot;
nt_text2 &lt;- &quot;/verein_id/3300/plus/0?hauptwettbewerb=&amp;wettbewerb_id=&amp;trainer_id=&amp;start=Aug+20%2C+2003&amp;ende=Feb+4%2C+2019&amp;nurEinsatz=2&quot;

#get all the goals scored by Cristiano Ronaldo
ronaldo &lt;- rbind(
  paste0(base_url, &quot;player_name&quot;, club_text1, 8198, club_text2) %&gt;%
    get_club_goals(),
  paste0(base_url, &quot;player_name&quot;, nt_text1, 8198, nt_text2) %&gt;%
    get_nt_goals()
)

#count the number of unique dates scored on
length(unique(ronaldo$date))</code></pre>
<pre><code>## [1] 244</code></pre>
<p>So Ronaldo has scored on 244 of the 366 possible days of the year. It’s not surprising that scoring on <em>every</em> day would be difficult. The club season only runs August-June and there are unlikely to be many possible games to pla in July at all. Plus days such a Christmas are usually taken off from football.</p>
<p>In terms of goals per day using 2019s calendar this looks like (plot made using the <a href="https://cran.r-project.org/web/packages/openair/index.html">openair package</a>:</p>
<pre class="r"><code>ronaldo %&gt;%
  #count goals per date
  group_by(date) %&gt;%
  summarise(goals = n()) %&gt;%
  #convert to 2019 dates
  mutate(date = as.Date(paste0(&quot;2019/&quot;, date))) %&gt;%
  #use calendarPlot from the openair package
  calendarPlot(., pollutant = &quot;goals&quot;, year = 2019)</code></pre>
<p><img src="/post/2019-03-05-The_Knowledge_3_files/figure-html/ronaldo_calendar-1.png" width="672" /></p>
<p>Which shows more deviation in scoring than I thought it would. Nethertheless, from Sepetember-May each year is pretty blocked out, though there is a run of Saturdays this December which could be fertile ground for increasing his total.</p>
<p>Next we need to get a list of likely players who could come close to matching Ronaldo’s record.</p>
<p>For this I took the first page of transfermarkt’s top scorers of the year across all leagues. It’s possible that a player might (e.g.) be on the second page each year and have scored a ton, but I don’t think it’s super likely.</p>
<p>I run this through the top scorers page from 1995 (the earliest year available) to 2018 and grab each player id. Afterwards, save the scraped list as an .rds to preventneeding to continually rescrape the page and put extra load onto the server.</p>
<pre class="r"><code>#the url for the pages of top scorers
top_scorer_ids &lt;- paste0(base_url, 
                         &quot;spieler-statistik/jahrestorschuetzen/&quot;,
                         &quot;statistik/stat/plus/0/galerie/0?jahr=&quot;,
                         1995:2018,
                         &quot;&amp;wettbewerb=alle&amp;monatVon=01&amp;monatBis=12&amp;altersklasse=&amp;&quot;,
                         &quot;land_id=&amp;ausrichtung=alle&amp;spielerposition_id=alle&amp;art=0&quot;) %&gt;%
  #scrape the ids of players
  lapply(., function(year) {
    read_html(year) %&gt;%
      html_nodes(&quot;#yw1 .spielprofil_tooltip&quot;) %&gt;%
      html_attr(&quot;id&quot;)
  }) %&gt;%
  unlist() %&gt;%
  unique()

#save this to prevent need for re-scraping
saveRDS(top_scorer_ids, &quot;transfermarkt_top_scorers.rds&quot;)</code></pre>
<p>Then all that’s left is to scrape the goals for each player whose id we’ve scraped. Again, save this once run, especially as it takes a fair while to complete. For this article the data was scraped on the 5th February 2019</p>
<pre class="r"><code>player_goals &lt;- top_scorer_ids %&gt;%
  #for each player scrape every goal
  lapply(., function(id) {
    goals &lt;- rbind(
      paste0(base_url, &quot;player_name&quot;, club_text1, id, club_text2) %&gt;%
        get_club_goals(),
      paste0(base_url, &quot;player_name&quot;, nt_text1, id, nt_text2) %&gt;%
        get_nt_goals()
    ) %&gt;%
      #remove NAS
      #this is where a player hasn&#39;t scored for their nation
      filter(!is.na(date)) %&gt;%
      mutate(id = id)
  }) %&gt;%
  do.call(rbind, .)

#and save
saveRDS(player_goals, &quot;top_scorer_goals.rds&quot;)</code></pre>
<p>Now we have a list of every goal scored by profilic strikers, we just have to group by each player and count how many dates they’ve scored on. To get the playest with the highest number of unique dates we group by their id and count the length of the unique dates they’ve scored on.</p>
<pre class="r"><code>days_per_player &lt;- player_goals %&gt;%
  #group by player
  group_by(id) %&gt;%
  #count the dates scored on
  summarise(days = length(unique(date))) %&gt;%
  arrange(-days) %&gt;%
  #rejoin the name data back in
  left_join(.,
            player_goals %&gt;%
              select(id, name) %&gt;%
              unique(),
            by = &quot;id&quot;) %&gt;%
  print()</code></pre>
<pre><code>## # A tibble: 413 x 3
##    id     days name             
##    &lt;chr&gt; &lt;int&gt; &lt;chr&gt;            
##  1 8198    244 Cristiano Ronaldo
##  2 28003   210 Messi            
##  3 7349    203 Raúl             
##  4 3455    200 Ibrahimovic      
##  5 3207    189 Henry            
##  6 4257    187 Eto&#39;o            
##  7 3924    173 Drogba           
##  8 48280   173 Cavani           
##  9 44352   172 Suárez           
## 10 7980    171 Villa            
## # ... with 403 more rows</code></pre>
<p>so perhaps unsurprisingly, Ronaldo comes out on top. As expected given the data source, most of the top players are very recent strikers- all of the top 10 were active well into the 2010s. <a href="https://en.wikipedia.org/wiki/Ulf_Kirsten">Ulf Kirsten</a> and <a href="https://en.wikipedia.org/wiki/Toni_Polster">Toni Polster</a> are the torchbearers for strikers from the 90s.</p>
<p>As always in these posts, I try to learn some new stuff as I do them. I thought this might be a good time to try some circular plotting. I don’t think the resultan</p>
<pre class="r"><code>circular_data &lt;- player_goals %&gt;%
  #filter out top 16 scorers
  filter(id %in% days_per_player$id[1:16]) %&gt;%
  #group by month and player and sum
  mutate(month = gsub(&quot;\\/.*&quot;, &quot;&quot;, date)) %&gt;%
  group_by(id, month, competition) %&gt;%
  summarise(goals = n()) %&gt;%
  left_join(.,
            player_goals %&gt;%
              select(id, name) %&gt;%
              unique(),
            by = &quot;id&quot;)

#too many competititon for legend
#sort out into broad groups
competition_types &lt;- data.frame(competition = circular_data$competition) %&gt;%
  unique() %&gt;%
  mutate(competition = as.character(competition)) %&gt;%
  mutate(competition_type = case_when(
    grepl(&quot;MLS&quot;, competition) ~ &quot;Domestic&quot;,
    grepl(&quot;World Cup qualification| Qualifiers&quot;, competition) ~ &quot;International&quot;,
    grepl(&quot;Friendlies&quot;, competition) ~ &quot;International Friendlies&quot;,
    grepl(&quot;World Cup [0-9]{4}|Confederations|EURO [0-9]{4}&quot;, competition) ~ &quot;International Tournament&quot;,
    grepl(&quot;UEFA|Champions League|UI Cup|Cup Winners|European Cup|Europa&quot;, competition) ~ &quot;European&quot;,
    grepl(&quot;Club World&quot;, competition) ~ &quot;International Club&quot;,
    grepl(&quot;Cup|cup|Pokal|copa|Copa|beker|Coupe|coppa|Kupasi|Trophée|Kupa&quot;, competition) ~ &quot;Domestic Cup&quot;
  )) %&gt;%
  mutate(competition_type = ifelse(is.na(competition_type), &quot;Domestic&quot;, competition_type)) %&gt;%
  #convert to factor for plot fill order
  mutate(competition_type = fct_rev(factor(competition_type)))

#plot as circular radar plots
circular_data %&gt;%
  left_join(., competition_types, by = &quot;competition&quot;) %&gt;%
  ggplot(., aes(x = month, y = goals, fill = competition_type)) +
  #convert to polar coordinates
  coord_polar(theta = &quot;x&quot;, start = -.13) +
  geom_bar(stat = &quot;identity&quot;) +
  scale_fill_discrete(name = &quot;Competition Type&quot;) +
  ggtitle(&quot;Goals Per Month for Top 16 Unique Day Scorers&quot;) +
  facet_wrap(~name) +
  theme_minimal() +
  theme(axis.text = element_blank())</code></pre>
<p><img src="/post/2019-03-05-The_Knowledge_3_files/figure-html/plot_circular-1.png" width="672" /></p>
<p>One nice thin that pops out is how Kirsten rarely scored in December/January- probably due to the Bundesliga mid season break.</p>
<p>I also found it interesting that <a href="https://en.wikipedia.org/wiki/Dirk_Kuyt">Dirk Kuyt</a> featured in the top 16, despite not being renowned as a great goalscorer.</p>
<pre class="r"><code>#count total goals per player
left_join(
  days_per_player,
  player_goals %&gt;%
    group_by(id) %&gt;%
    summarise(goals = n()),
  by = &quot;id&quot;
) %&gt;%
  #work out days/total goals
  mutate(proportion_unique = days / goals) %&gt;%
  arrange(-days) %&gt;%
  filter(days &gt; 150) %&gt;%
  select(name, goals, days, proportion_unique) %&gt;%
  arrange(-proportion_unique)</code></pre>
<pre><code>## # A tibble: 34 x 4
##    name      goals  days proportion_unique
##    &lt;chr&gt;     &lt;int&gt; &lt;int&gt;             &lt;dbl&gt;
##  1 Gilardino   231   154             0.667
##  2 Cissé       269   166             0.617
##  3 Signori     260   160             0.615
##  4 Di Vaio     269   165             0.613
##  5 Toni        273   165             0.604
##  6 Kuyt        281   169             0.601
##  7 Lampard     258   154             0.597
##  8 Frei        257   153             0.595
##  9 Drogba      300   173             0.577
## 10 Trézéguet   265   152             0.574
## # ... with 24 more rows</code></pre>
<p>When sorted by how evenly their goals/date coverage is (i.e. the ideal ratio would be 1 goal on every day), Dirk Kuyt pops up again (and did in fact score many more goals than I had assumed). <a href="https://en.wikipedia.org/wiki/Alberto_Gilardino">Alberto Gilardino</a> really stands out as a player who has maximum date coverage desite (relative to other members of the list!) a low number of total goals scored.</p>
<p>I’m not sure what, if any, insight that adds but is a cool piece of trivia.</p>
</div>
<div id="first-losers" class="section level1">
<h1>First Losers</h1>
<blockquote class="twitter-tweet" data-lang="en">
<p lang="en" dir="ltr">
Which club holds the record for most 2nd place finishes in the English top flight?
</p>
— Tom Goddard (<span class="citation">@Tom_Goddard_13</span>) <a href="https://twitter.com/Tom_Goddard_13/status/1092785174046228480?ref_src=twsrc%5Etfw">February 5, 2019</a>
</blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<p>The fist question this week involving final positions ask which teams have finished second the most.</p>
<p>First lets load up the engsoccerdata for English leagues 1882-2016. I’ve munged it in a pretty verbose way; there’s definitely a faster way to do it but that’s not really necessary. All we need are the indicators used to sort the league (points, goal difference, and goal scored) for every match in a long format.</p>
<pre class="r"><code>eng_data &lt;- engsoccerdata::england %&gt;%
  #select only pertinent variables
  select(Date, Season, home, visitor, hgoal, vgoal, division) %&gt;%
  rename_all(tolower) %&gt;%
  #melt the data to long format
  reshape2::melt(id.vars = c(&quot;date&quot;, &quot;season&quot;, &quot;hgoal&quot;, &quot;vgoal&quot;, &quot;division&quot;),
                 value.name = &quot;team&quot;, variable.name = &quot;location&quot;) %&gt;%
  #this can be done in one step but for sanity
  mutate(result = case_when(
    hgoal &gt; vgoal &amp; location == &quot;home&quot; ~ &quot;W&quot;,
    vgoal &gt; hgoal &amp; location == &quot;visitor&quot; ~ &quot;W&quot;,
    hgoal &lt; vgoal &amp; location == &quot;home&quot; ~ &quot;L&quot;,
    vgoal &lt; hgoal &amp; location == &quot;visitor&quot; ~ &quot;L&quot;,
    vgoal == hgoal ~ &quot;D&quot;
  )) %&gt;%
  #points for a win changed in 1981
  mutate(points = case_when(
    result == &quot;L&quot; ~ 0,
    result == &quot;D&quot; ~ 1,
    result == &quot;W&quot; &amp; season &lt; 1981 ~ 2,
    result == &quot;W&quot; &amp; season &gt; 1980 ~ 3
  )) %&gt;%
  #and get the goal info too
  mutate(goal_diff = case_when(
    location == &quot;home&quot; ~ hgoal - vgoal,
    location == &quot;visitor&quot; ~ vgoal - hgoal
  )) %&gt;%
  mutate(goals = case_when(
    location == &quot;home&quot; ~ hgoal,
    location == &quot;visitor&quot; ~ vgoal
  )) %&gt;%
  #only save the variables we care about then sort
  select(date, season, division, team, points, goals, goal_diff) %&gt;%
  arrange(date, team)</code></pre>
<p>Then find the final positions of each team in each season of English football sorted by points, goal difference and goals for</p>
<pre class="r"><code>final_positions &lt;- eng_data %&gt;%
  setDT() %&gt;%
  #find the match number
  .[, match := 1:.N, by = c(&quot;season&quot;, &quot;team&quot;)] %&gt;%
  #find the cumulative points, goal difference and goals for
  .[, season_points := cumsum(points), by = c(&quot;season&quot;, &quot;team&quot;)] %&gt;%
  .[, season_gd := cumsum(goal_diff), by = c(&quot;season&quot;, &quot;team&quot;)] %&gt;%
  .[, season_g := cumsum(goals), by = c(&quot;season&quot;, &quot;team&quot;)] %&gt;%
  #filter out the final matches totals and order
  .[.[, .I[match == max(match)], by= c(&quot;season&quot;, &quot;division&quot;)]$V1] %&gt;%
  .[order(season, division, -season_points)] %&gt;%
  #assign the final positions
  .[, final_position := 1:.N, by = c(&quot;season&quot;, &quot;division&quot;)] %&gt;%
  .[, c(&quot;team&quot;, &quot;division&quot;, &quot;final_position&quot;)] %&gt;%
  #count by final position
  .[, pos_count := .N, by = c(&quot;team&quot;, &quot;division&quot;, &quot;final_position&quot;)] %&gt;%
  unique()</code></pre>
<p>Then we can filter out those who have finished second most</p>
<pre class="r"><code>second_place &lt;- final_positions %&gt;%
  #filter out second place finishes
  .[final_position == 2] %&gt;%
  .[, c(&quot;team&quot;, &quot;division&quot;, &quot;final_position&quot;, &quot;pos_count&quot;)] %&gt;%
  .[order(-pos_count)] %&gt;%
  print()</code></pre>
<pre><code>##                    team division final_position pos_count
##   1:  Manchester United        1              2        14
##   2:            Arsenal        1              2        12
##   3:          Liverpool        1              2        11
##   4:        Aston Villa        1              2         9
##   5:   Sheffield United        2              2         8
##  ---                                                     
## 202:           Rochdale        4              2         1
## 203: Milton Keynes Dons        3              2         1
## 204:      Burton Albion        3              2         1
## 205:      Oxford United        4              2         1
## 206:         Portsmouth        4              2         1</code></pre>
<p>Perhaps unsurprisingly, most of the teams to finish second have finished second in the top flight. Manchester United lead the way with Arsenal and Liverpool following up.</p>
<p>Bristol City, Charlton Athletic, Oldham Athletic, Blackpool, QPR, Watford and Southampton have finished runners up in the top division without winning it, all having acheived this exactly once.</p>
<p>Plymouth Argyle have perhaps the most heartbreaking run of all though- having finished second in the old 3rd Division South SIX times in a row between 1922-1927 before finally winning it in 1929.</p>
<p>I thought I might as well also plot every teams league finishes as a proportion of their season in the league. Position here refers to total overall position (so 1st in Division two might be 21st overall). The darker the colour, the more likely the team was the end the season in that position. All teams have been sorted by their mean final league position.</p>
<pre class="r"><code>eng_data %&gt;%
  filter(season &gt; 1991) %&gt;%
  setDT() %&gt;%
  .[, match := 1:.N, by = c(&quot;season&quot;, &quot;team&quot;)] %&gt;%
  .[, season_points := cumsum(points), by = c(&quot;season&quot;, &quot;team&quot;)] %&gt;%
  .[, season_gd := cumsum(goal_diff), by = c(&quot;season&quot;, &quot;team&quot;)] %&gt;%
  .[, season_g := cumsum(goals), by = c(&quot;season&quot;, &quot;team&quot;)] %&gt;%
  .[.[, .I[match == max(match)], by= c(&quot;season&quot;, &quot;division&quot;)]$V1] %&gt;%
  .[order(season, division, -season_points)] %&gt;%
  .[, final_position := 1:.N, by = c(&quot;season&quot;, &quot;division&quot;)] %&gt;%
  .[, total_position := 1:.N, by = c(&quot;season&quot;)] %&gt;%
  .[, c(&quot;team&quot;, &quot;division&quot;, &quot;final_position&quot;, &quot;total_position&quot;)] %&gt;%
  .[, pos_count := .N, by = c(&quot;team&quot;, &quot;division&quot;, &quot;final_position&quot;)] %&gt;%
  .[, team_appearances := .N, by = c(&quot;team&quot;)] %&gt;%
  .[, mean_pos := sum(total_position)/team_appearances, by = c(&quot;team&quot;)] %&gt;%
  unique() %&gt;%
  .[order(mean_pos)] %&gt;%
  .[, team := fct_rev(fct_relevel(as.factor(team), unique(.$team)))] %&gt;%
  ggplot(., aes(x = total_position, y = team)) + 
  geom_tile(aes(alpha = pos_count/team_appearances), fill = &quot;blue&quot;) +
  scale_alpha_continuous(guide = FALSE) +
  ggtitle(&quot;Teams Ordered by Mean Final Position 1992-2016&quot;,
          subtitle = &quot;Weight indicates proportion of finishes in that position&quot;) +
  xlab(&quot;Total League Position&quot;) +
  theme_minimal() +
  theme(axis.text.y = element_text(angle = 10))</code></pre>
<p><img src="/post/2019-03-05-The_Knowledge_3_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
</div>
<div id="slip-slidin-away" class="section level1">
<h1>Slip Slidin’ Away</h1>
<blockquote class="twitter-tweet" data-lang="en">
<p lang="en" dir="ltr">
As we're starting to reach that time of season (we'll, we are at <a href="https://twitter.com/hashtag/itfc?src=hash&amp;ref_src=twsrc%5Etfw">#itfc</a>)… What's the earliest <em>collectively</em> a team from each of the top 4 English leagues has been relegated?
</p>
— Philip Genochio (<span class="citation">@philipgenochio</span>) <a href="https://twitter.com/philipgenochio/status/1092782376852156416?ref_src=twsrc%5Etfw">February 5, 2019</a>
</blockquote>
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
<p>A similar question involves the earliest teams to get relegated. Obviously for this first we need to know how many teams are relegated from each league per season. Having only really started watching football around the turn of the millenium I was a bit surprised how much this has changed over the years (n.b. I’m only counting automatic relegation- playoffs and re-elections don’t count).</p>
<pre class="r"><code>#manually enter the number of relegation spots per league
relegation_spots &lt;- eng_data %&gt;%
  .[, c(&quot;season&quot;, &quot;division&quot;)] %&gt;%
  unique() %&gt;%
  mutate(relegation_spots = case_when(
    season &gt;= 1995 &amp; division == 1 ~ 3,
    season &gt;= 1994 &amp; division == 1 ~ 4,
    season &gt;= 1991 &amp; division == 1 ~ 3,
    season &gt;= 1990 &amp; division == 1 ~ 2,
    season &gt;= 1973 &amp; division == 1 ~ 3,
    season &gt;= 1898 &amp; division == 1 ~ 2,
    season &gt;= 1995 &amp; division == 2 ~ 3,
    season &gt;= 1994 &amp; division == 2 ~ 4,
    season &gt;= 1991 &amp; division == 2 ~ 3,
    season &gt;= 1990 &amp; division == 2 ~ 2,
    season &gt;= 1988 &amp; division == 2 ~ 3,
    season &gt;= 1986 &amp; division == 2 ~ 2,
    season &gt;= 1973 &amp; division == 2 ~ 3,
    season &gt;= 1921 &amp; division == 2 ~ 2,
    season &gt;= 1920 &amp; division == 2 ~ 1,
    season &gt;= 1919 &amp; division == 2 ~ 3,
    season &gt;= 1995 &amp; division == 3 ~ 4,
    season &gt;= 1994 &amp; division == 3 ~ 5,
    season &gt;= 1991 &amp; division == 3 ~ 4,
    season &gt;= 1990 &amp; division == 3 ~ 3,
    season &gt;= 1988 &amp; division == 3 ~ 4,
    season &gt;= 1986 &amp; division == 3 ~ 3,
    season &gt;= 1958 &amp; division == 3 ~ 4,
    season &gt;= 2002 &amp; division == 4 ~ 2,
    season &gt;= 1996 &amp; division == 4 ~ 1,
    season &gt;= 1993 &amp; division == 4 ~ 0,
    season &gt;= 1992 &amp; division == 4 ~ 1,
    season &gt;= 1990 &amp; division == 4 ~ 0,
    season &gt;= 1986 &amp; division == 4 ~ 1
 )) %&gt;%
  mutate(relegation_spots = ifelse(relegation_spots == 0, NA, relegation_spots))</code></pre>
<p>We then need to work out how many points each team has, and how many they could possibly achieve, after every match in a season.</p>
<pre class="r"><code>possible_positions &lt;- eng_data %&gt;%
    setDT() %&gt;%
  #get the match number
  .[, match := 1:.N, by = c(&quot;season&quot;, &quot;team&quot;)] %&gt;%
  #get the current points for the team
  .[, season_points := cumsum(points), by = c(&quot;season&quot;, &quot;team&quot;)] %&gt;%
  .[order(division, season, match, -season_points)] %&gt;%
  #get the current position for the team
  .[, position := 1:.N, by = c(&quot;division&quot;, &quot;season&quot;, &quot;match&quot;)] %&gt;%
  #how many teams are in the league
  .[, teams := max(position), by = c(&quot;division&quot;, &quot;season&quot;)] %&gt;%
  #find how many matches each team has left to play
  .[, matches_remaining := max(match) - match, by = c(&quot;division&quot;, &quot;season&quot;)] %&gt;%
  #the max points assumes each team wins all of their remaining matches
  .[season &lt; 1981, possible_points := season_points + (matches_remaining * 2)] %&gt;%
  .[season &gt; 1980, possible_points := season_points + (matches_remaining * 3)] %&gt;%
  #merge in the relegation spots and find what position each team needs to be safe
  merge(., relegation_spots, by = c(&quot;division&quot;, &quot;season&quot;)) %&gt;%
  .[, lowest_safe_position := teams - relegation_spots] %&gt;%
  #the threshold for safety is the number of points the lowest safe team has
  .[position == lowest_safe_position, lowest_safe_points := season_points]</code></pre>
<p>Then it’s a simple case of finding teams in the relgation zone and finding the point at which they can no longer catch the lowest safe team</p>
<pre class="r"><code>relegation_secured &lt;- possible_positions %&gt;%
  #filter out teams in relegation trouble
  .[!is.na(lowest_safe_position)] %&gt;%
  .[position &gt;= lowest_safe_position] %&gt;%
  .[, lowest_safe_points := na.locf(lowest_safe_points)] %&gt;%
  .[possible_points &lt; lowest_safe_points] %&gt;%
    .[, c(&quot;season&quot;, &quot;division&quot;, &quot;team&quot;, &quot;season_points&quot;,
          &quot;matches_remaining&quot;, &quot;possible_points&quot;, &quot;lowest_safe_points&quot;)] %&gt;%
  .[order(-matches_remaining)] %&gt;%
  #remove duplicates
  .[!duplicated(paste0(season, division, team))] %&gt;%
  print()</code></pre>
<pre><code>##      season division              team season_points matches_remaining
##   1:   1973        3          Rochdale            16                 8
##   2:   1984        1        Stoke City            17                 7
##   3:   2001        2  Stockport County            17                 7
##   4:   2003        2         Wimbledon            21                 7
##   5:   2016        2  Rotherham United            17                 7
##  ---                                                                  
## 709:   2009        4      Grimsby Town            44                 0
## 710:   2010        4      Lincoln City            47                 0
## 711:   2011        4   Hereford United            44                 0
## 712:   2012        4         Aldershot            48                 0
## 713:   2016        4 Hartlepool United            46                 0
##      possible_points lowest_safe_points
##   1:              32                 33
##   2:              38                 40
##   3:              38                 39
##   4:              42                 44
##   5:              38                 41
##  ---                                   
## 709:              44                 48
## 710:              47                 48
## 711:              44                 46
## 712:              48                 51
## 713:              46                 48</code></pre>
<p>So Rochdale hold the questionable honour of being the team knowing they are doomed with the most matches to go (with 8 in division 3 in 1973). There’s quite a large chasing pack of teams who have known with 7 or 6 matches left too. Ipswich are currently ‘only’ 8 points off of safety with 16 games left to go so seems unlikely to beat 8 but it could be close…</p>
<p>I also wanted to see what the earliest a team has ever been certain of their final position is.</p>
<pre class="r"><code>certain_final_positions &lt;- possible_positions %&gt;%
  #find the possible points for the teams above and below each team
  .[, poss_points_nextworst := lead(possible_points), by = c(&quot;season&quot;, &quot;division&quot;, &quot;match&quot;)] %&gt;%
  .[, points_nextbest := lag(season_points), by = c(&quot;season&quot;, &quot;division&quot;, &quot;match&quot;)] %&gt;%
  #filter out teams that cannot beat/fall below the next best/worst teams
  .[(is.na(poss_points_nextworst) | season_points &gt; poss_points_nextworst) &amp; 
      (is.na(points_nextbest) | possible_points &lt; points_nextbest) &amp;
      matches_remaining &gt; 0] %&gt;%
  #order and select columns
  .[order(-matches_remaining)] %&gt;%
  .[, c(&quot;division&quot;, &quot;season&quot;, &quot;team&quot;, &quot;position&quot;, &quot;matches_remaining&quot;, &quot;teams&quot;)] %&gt;%
  print()</code></pre>
<pre><code>##       division season                 team position matches_remaining
##    1:        4   1968 Bradford Park Avenue       24                 7
##    2:        1   1984           Stoke City       22                 6
##    3:        2   1949    Tottenham Hotspur        1                 6
##    4:        2   1971              Watford       22                 6
##    5:        2   1973        Middlesbrough        1                 6
##   ---                                                                
## 1458:        4   2014    Hartlepool United       22                 1
## 1459:        4   2015     Northampton Town        1                 1
## 1460:        4   2015        AFC Wimbledon        7                 1
## 1461:        4   2015               Barnet       15                 1
## 1462:        4   2016        Leyton Orient       24                 1
##       teams
##    1:    24
##    2:    22
##    3:    22
##    4:    22
##    5:    22
##   ---      
## 1458:    24
## 1459:    24
## 1460:    24
## 1461:    24
## 1462:    24</code></pre>
<p>Spare a thought for fans of Bradford Park Avenue in 1968-1969 who knew their team would finish bottom of the 3rd Division North with 7 matches (of 46) remaining. Luckily they wern’t relegated as they were already in the bottom division of the football league and we re-elected for the next season. They repeated this feat, now in Division 4, 5 years later, finishing bottom with 6 games to go.</p>
<p>Most of these involve teams either winning or finishing bottom of their league. If we filter these out we’re left with:</p>
<pre class="r"><code>certain_final_positions %&gt;%
  .[position != 1 &amp; position != teams]</code></pre>
<pre><code>##      division season              team position matches_remaining teams
##   1:       3a   1931      New Brighton       20                 4    22
##   2:       3a   1931          Rochdale       21                 4    22
##   3:        2   2003     Bradford City       23                 3    24
##   4:        2   2005  Sheffield United        2                 3    24
##   5:       3a   1931      New Brighton       20                 3    22
##  ---                                                                   
## 446:        4   2013    Fleetwood Town        4                 1    24
## 447:        4   2014 Stevenage Borough        6                 1    24
## 448:        4   2014 Hartlepool United       22                 1    24
## 449:        4   2015     AFC Wimbledon        7                 1    24
## 450:        4   2015            Barnet       15                 1    24</code></pre>
<p>Which really emphasises how only exceptionally good/bad teams are ever really certain of their position before the end of the season.</p>
</div>
<div id="draw-me-like-one-of-your" class="section level1">
<h1>Draw Me Like One of Your</h1>
<p><a href="https://www.theguardian.com/football/2019/feb/06/what-are-the-lowest-xg-scoring-football-matches-in-history-expected-goals-the-knowledge-football">““Tottenham have currently played 29 consecutive Premier League games without drawing one,” notes Wouter van Dael. “What is the longest ever such league run?””</a></p>
<pre class="r"><code>draws &lt;- eng_data %&gt;%
  .[order(team, date)] %&gt;%
  .[, game_id := 1:.N, by = team] %&gt;%
  .[goal_diff != 0] %&gt;%
  .[, consecutive := lead(game_id) - game_id, by = team] %&gt;%
  .[consecutive != 1, consecutive := NA] %&gt;%
  .[, count := .N*!is.na(consecutive), rleid(!is.na(consecutive))] %&gt;%
  .[count != lead(count)] %&gt;%
  .[, c(&quot;date&quot;, &quot;season&quot;, &quot;division&quot;, &quot;team&quot;, &quot;count&quot;)] %&gt;%
  .[order(-count)] %&gt;%
  print()</code></pre>
<pre><code>##               date season division                 team count
##      1: 1892-12-10   1892        1          Aston Villa    50
##      2: 1896-11-09   1896        1           Stoke City    45
##      3: 1909-02-27   1908        1           Sunderland    45
##      4: 1914-02-14   1913        2 Bradford Park Avenue    43
##      5: 1910-03-25   1909        2       Leicester City    43
##     ---                                                      
## 108806: 2015-09-05   2015        4            York City     0
## 108807: 2015-10-17   2015        4            York City     0
## 108808: 2015-12-19   2015        4            York City     0
## 108809: 2016-01-16   2015        4            York City     0
## 108810: 2016-03-28   2015        4            York City     0</code></pre>
<p>Tottenham’s run without a draw doesn’t even make the top 25 such runs! ANd they still would have to wait until at least next season until they can match Aston Villa’s run from New Years Day 1891 until Christmas Eve in 1892, a run of 50 matches without a draw- a run that included 23 losses, and 27 wins.</p>
</div>

      </div>

      


<div class="article-tags">
  
  <a class="btn btn-primary btn-outline" href="/tags/maps">maps</a>
  
  <a class="btn btn-primary btn-outline" href="/tags/pubs">pubs</a>
  
  <a class="btn btn-primary btn-outline" href="/tags/cambridge">cambridge</a>
  
</div>



    </div>
  </div>

</article>



<div class="article-container article-widget">
  <div class="hr-light"></div>
  <h3>Related</h3>
  <ul>
    
    <li><a href="/post/cambridge_pub_crawl/">Planning a Pub Crawl Using R</a></li>
    
    <li><a href="/post/counties_league_points/">Which English County Has Won the Most Points</a></li>
    
    <li><a href="/post/getis-ord-heatmaps-tutorial/">How I Learned To Stop Worrying and Love Heatmaps</a></li>
    
    <li><a href="/post/sf.schlorodot/">sf.chlorodot mini-package</a></li>
    
  </ul>
</div>




<div class="article-container">
  

</div>

<footer class="site-footer">
  <div class="container">
    <p class="powered-by">

      &copy; 2018 &middot; 

      Powered by the
      <a href="https://sourcethemes.com/academic/" target="_blank" rel="noopener">Academic theme</a> for
      <a href="https://gohugo.io" target="_blank" rel="noopener">Hugo</a>.

      <span class="pull-right" aria-hidden="true">
        <a href="#" id="back_to_top">
          <span class="button_icon">
            <i class="fa fa-chevron-up fa-2x"></i>
          </span>
        </a>
      </span>

    </p>
  </div>
</footer>


<div id="modal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close btn-large" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Cite</h4>
      </div>
      <div>
        <pre><code class="modal-body tex"></code></pre>
      </div>
      <div class="modal-footer">
        <a class="btn btn-primary btn-outline js-copy-cite" href="#" target="_blank">
          <i class="fa fa-copy"></i> Copy
        </a>
        <a class="btn btn-primary btn-outline js-download-cite" href="#" target="_blank">
          <i class="fa fa-download"></i> Download
        </a>
        <div id="modal-error"></div>
      </div>
    </div>
  </div>
</div>

    

    
    

    

    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js" integrity="sha512-3P8rXCuGJdNZOnUx/03c1jOTnMn3rP63nBip5gOP2qmUh5YAdVAvFZ1E+QLZZbC1rtMrQb+mah3AfYW11RUrWA==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.imagesloaded/4.1.3/imagesloaded.pkgd.min.js" integrity="sha512-umsR78NN0D23AzgoZ11K7raBD+R6hqKojyBZs1w8WvYlsI+QuKRGBx3LFCwhatzBunCjDuJpDHwxD13sLMbpRA==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha512-iztkobsvnjKfAtTNdHkGVjAYTrrtlC7mGp/54c40wowO7LhURYl3gVzzcEqGl/qKXQltJ2HwMrdLcNUdo+N/RQ==" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.4/isotope.pkgd.min.js" integrity="sha512-VDBOIlDbuC4VWxGJNmuFRQ0Li0SKkDpmGyuhAG5LTDLd/dJ/S0WMVxriR2Y+CyPL5gzjpN4f/6iqWVBJlht0tQ==" crossorigin="anonymous"></script>
    
    
    <script src="/js/hugo-academic.js"></script>
    

    
    
      
      
      <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js" integrity="sha256-/BfiIkHlHoVihZdc6TFuj7MmJ0TWcWsMXkeDFwhi0zw=" crossorigin="anonymous"></script>
      

      

      

      <script>hljs.initHighlightingOnLoad();</script>
    

    
    
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({ tex2jax: { inlineMath: [['$','$'], ['\\(','\\)']] } });
    </script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_CHTML" integrity="sha512-tOav5w1OjvsSJzePRtt2uQPFwBoHt1VZcUq8l8nm5284LEKE9FSJBQryzMBzHxY5P0zRdNqEcpLIRVYFNgu1jw==" crossorigin="anonymous"></script>
    
    

  </body>
</html>

